/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {0, 0, 1};
static const casadi_int casadi_s2[3] = {53, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_zeros[34] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* quadrotor_cost_ext_cost_e_fun_jac:(i0[15],i1[],i2[],i3[53])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+9, w02, w03, *w04=w+19, *w05=w+22, w07, w08, w09, w10, *w11=w+53;
  casadi_real w12, w13, *w14=w+59, *w15=w+63, *w16=w+67, *w17=w+71, *w18=w+87, *w19=w+103, *w20=w+135, *w21=w+167, *w22=w+183, *w23=w+215;
  casadi_real *w24=w+279, w25, w26, w27, w28, w29, w30, w31, w32, w33, *w34=w+352, *w35=w+367;
  casadi_real *w36=w+375, w37, w38, w39, w40, *w41=w+382, w42, *w44=w+421, *w45=w+424, *w46=w+427, *w47=w+436, *w48=w+439;
  casadi_real *w49=w+442, *w50=w+451, *w51=w+460, *w52=w+468, *w53=w+476;
  const casadi_real *cs, *ct, *wr06, *wr43, *wr45, *wr48;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w01, 8);
  /* #2: @2 = 0 */
  w02 = 0.;
  /* #3: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #4: @4 = all_2.22045e-16(3x1) */
  casadi_fill(w04, 3, 2.2204460492503131e-16);
  /* #5: @5 = zeros(8x1) */
  casadi_clear(w05, 8);
  /* #6: @6 = input[3][0] */
  wr06 = arg[3] ? arg[3] : casadi_zeros;
  /* #7: @7 = @6[0] */
  w07 = wr06[0];
  /* #8: @8 = @6[1] */
  w08 = wr06[1];
  /* #9: @9 = @6[2] */
  w09 = wr06[2];
  /* #10: @10 = @6[3] */
  w10 = wr06[3];
  /* #11: @11 = horzcat(@7, @8, @9, @10) */
  rr=w11;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  /* #12: @11 = @11' */
  /* #13: @7 = (-@8) */
  w07 = (- w08 );
  /* #14: @12 = @6[0] */
  w12 = wr06[0];
  /* #15: @13 = (-@9) */
  w13 = (- w09 );
  /* #16: @14 = horzcat(@7, @12, @10, @13) */
  rr=w14;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w13;
  /* #17: @14 = @14' */
  /* #18: @10 = (-@10) */
  w10 = (- w10 );
  /* #19: @12 = @6[0] */
  w12 = wr06[0];
  /* #20: @15 = horzcat(@13, @10, @12, @8) */
  rr=w15;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w08;
  /* #21: @15 = @15' */
  /* #22: @13 = @6[0] */
  w13 = wr06[0];
  /* #23: @16 = horzcat(@10, @9, @7, @13) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w13;
  /* #24: @16 = @16' */
  /* #25: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #26: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #27: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #28: @19 = horzcat(@18, @17) */
  rr=w19;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #29: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #30: @10 = @6[4] */
  w10 = wr06[4];
  /* #31: @9 = @6[5] */
  w09 = wr06[5];
  /* #32: @7 = @6[6] */
  w07 = wr06[6];
  /* #33: @13 = @6[7] */
  w13 = wr06[7];
  /* #34: @11 = horzcat(@10, @9, @7, @13) */
  rr=w11;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w13;
  /* #35: @11 = @11' */
  /* #36: @10 = (-@9) */
  w10 = (- w09 );
  /* #37: @12 = @6[4] */
  w12 = wr06[4];
  /* #38: @8 = (-@7) */
  w08 = (- w07 );
  /* #39: @14 = horzcat(@10, @12, @13, @8) */
  rr=w14;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w08;
  /* #40: @14 = @14' */
  /* #41: @13 = (-@13) */
  w13 = (- w13 );
  /* #42: @12 = @6[4] */
  w12 = wr06[4];
  /* #43: @15 = horzcat(@8, @13, @12, @9) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w09;
  /* #44: @15 = @15' */
  /* #45: @8 = @6[4] */
  w08 = wr06[4];
  /* #46: @16 = horzcat(@13, @7, @10, @8) */
  rr=w16;
  *rr++ = w13;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w08;
  /* #47: @16 = @16' */
  /* #48: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #49: @21 = @17' */
  for (i=0, rr=w21, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #50: @19 = horzcat(@21, @18) */
  rr=w19;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #51: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #52: @23 = horzcat(@20, @22) */
  rr=w23;
  for (i=0, cs=w20; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  /* #53: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #54: @13 = input[0][0] */
  w13 = arg[0] ? arg[0][0] : 0;
  /* #55: @7 = input[0][1] */
  w07 = arg[0] ? arg[0][1] : 0;
  /* #56: @10 = input[0][2] */
  w10 = arg[0] ? arg[0][2] : 0;
  /* #57: @8 = input[0][3] */
  w08 = arg[0] ? arg[0][3] : 0;
  /* #58: @12 = input[0][4] */
  w12 = arg[0] ? arg[0][4] : 0;
  /* #59: @9 = input[0][5] */
  w09 = arg[0] ? arg[0][5] : 0;
  /* #60: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #61: @26 = input[0][7] */
  w26 = arg[0] ? arg[0][7] : 0;
  /* #62: @27 = input[0][8] */
  w27 = arg[0] ? arg[0][8] : 0;
  /* #63: @28 = input[0][9] */
  w28 = arg[0] ? arg[0][9] : 0;
  /* #64: @29 = input[0][10] */
  w29 = arg[0] ? arg[0][10] : 0;
  /* #65: @30 = input[0][11] */
  w30 = arg[0] ? arg[0][11] : 0;
  /* #66: @31 = input[0][12] */
  w31 = arg[0] ? arg[0][12] : 0;
  /* #67: @32 = input[0][13] */
  w32 = arg[0] ? arg[0][13] : 0;
  /* #68: @33 = input[0][14] */
  w33 = arg[0] ? arg[0][14] : 0;
  /* #69: @34 = vertcat(@13, @7, @10, @8, @12, @9, @25, @26, @27, @28, @29, @30, @31, @32, @33) */
  rr=w34;
  *rr++ = w13;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  /* #70: @35 = @34[:8] */
  for (rr=w35, cs=w34+0; cs!=w34+8; cs+=1) *rr++ = *cs;
  /* #71: @5 = mac(@24,@35,@5) */
  for (i=0, rr=w05; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w24+j, ct=w35+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #72: @36 = @5[1:4] */
  for (rr=w36, cs=w05+1; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #73: @4 = (@4+@36) */
  for (i=0, rr=w04, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #74: @13 = ||@4||_F */
  w13 = casadi_norm_2(3, w04);
  /* #75: @7 = @5[0] */
  for (rr=(&w07), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #76: @10 = atan2(@13,@7) */
  w10  = atan2(w13,w07);
  /* #77: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #78: @8 = (@3*@10) */
  w08  = (w03*w10);
  /* #79: @12 = @5[1] */
  for (rr=(&w12), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #80: @9 = (@8*@12) */
  w09  = (w08*w12);
  /* #81: @9 = (@9/@13) */
  w09 /= w13;
  /* #82: @25 = 0.5 */
  w25 = 5.0000000000000000e-01;
  /* #83: @26 = (@25*@10) */
  w26  = (w25*w10);
  /* #84: @27 = @5[2] */
  for (rr=(&w27), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #85: @28 = (@26*@27) */
  w28  = (w26*w27);
  /* #86: @28 = (@28/@13) */
  w28 /= w13;
  /* #87: @29 = 0.5 */
  w29 = 5.0000000000000000e-01;
  /* #88: @10 = (@29*@10) */
  w10  = (w29*w10);
  /* #89: @30 = @5[3] */
  for (rr=(&w30), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #90: @31 = (@10*@30) */
  w31  = (w10*w30);
  /* #91: @31 = (@31/@13) */
  w31 /= w13;
  /* #92: @32 = 0 */
  w32 = 0.;
  /* #93: @33 = 0.5 */
  w33 = 5.0000000000000000e-01;
  /* #94: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #95: @37 = @5[4] */
  for (rr=(&w37), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #96: @38 = @5[5] */
  for (rr=(&w38), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #97: @38 = (-@38) */
  w38 = (- w38 );
  /* #98: @39 = @5[6] */
  for (rr=(&w39), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #99: @39 = (-@39) */
  w39 = (- w39 );
  /* #100: @40 = @5[7] */
  for (rr=(&w40), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #101: @40 = (-@40) */
  w40 = (- w40 );
  /* #102: @14 = horzcat(@37, @38, @39, @40) */
  rr=w14;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #103: @14 = @14' */
  /* #104: @37 = @5[5] */
  for (rr=(&w37), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #105: @38 = @5[4] */
  for (rr=(&w38), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #106: @39 = @5[7] */
  for (rr=(&w39), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #107: @39 = (-@39) */
  w39 = (- w39 );
  /* #108: @40 = @5[6] */
  for (rr=(&w40), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #109: @15 = horzcat(@37, @38, @39, @40) */
  rr=w15;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #110: @15 = @15' */
  /* #111: @37 = @5[6] */
  for (rr=(&w37), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #112: @38 = @5[7] */
  for (rr=(&w38), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #113: @39 = @5[4] */
  for (rr=(&w39), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #114: @40 = @5[5] */
  for (rr=(&w40), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #115: @40 = (-@40) */
  w40 = (- w40 );
  /* #116: @16 = horzcat(@37, @38, @39, @40) */
  rr=w16;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #117: @16 = @16' */
  /* #118: @37 = @5[7] */
  for (rr=(&w37), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #119: @38 = @5[6] */
  for (rr=(&w38), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #120: @38 = (-@38) */
  w38 = (- w38 );
  /* #121: @39 = @5[5] */
  for (rr=(&w39), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #122: @40 = @5[4] */
  for (rr=(&w40), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #123: @41 = horzcat(@37, @38, @39, @40) */
  rr=w41;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #124: @41 = @41' */
  /* #125: @21 = horzcat(@14, @15, @16, @41) */
  rr=w21;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<4; ++i) *rr++ = *cs++;
  /* #126: @18 = @21' */
  for (i=0, rr=w18, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #127: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #128: @37 = @5[0] */
  for (rr=(&w37), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #129: @38 = @5[1] */
  for (rr=(&w38), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #130: @38 = (-@38) */
  w38 = (- w38 );
  /* #131: @39 = @5[2] */
  for (rr=(&w39), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #132: @39 = (-@39) */
  w39 = (- w39 );
  /* #133: @40 = @5[3] */
  for (rr=(&w40), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #134: @40 = (-@40) */
  w40 = (- w40 );
  /* #135: @14 = vertcat(@37, @38, @39, @40) */
  rr=w14;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #136: @11 = mac(@18,@14,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w18+j, ct=w14+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #137: @37 = @11[1] */
  for (rr=(&w37), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #138: @37 = (@33*@37) */
  w37  = (w33*w37);
  /* #139: @38 = 0.5 */
  w38 = 5.0000000000000000e-01;
  /* #140: @39 = @11[2] */
  for (rr=(&w39), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #141: @39 = (@38*@39) */
  w39  = (w38*w39);
  /* #142: @40 = 0.5 */
  w40 = 5.0000000000000000e-01;
  /* #143: @42 = @11[3] */
  for (rr=(&w42), cs=w11+3; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #144: @42 = (@40*@42) */
  w42  = (w40*w42);
  /* #145: @5 = vertcat(@2, @9, @28, @31, @32, @37, @39, @42) */
  rr=w05;
  *rr++ = w02;
  *rr++ = w09;
  *rr++ = w28;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w37;
  *rr++ = w39;
  *rr++ = w42;
  /* #146: @35 = @5' */
  casadi_copy(w05, 8, w35);
  /* #147: @24 = zeros(8x8) */
  casadi_clear(w24, 64);
  /* #148: @43 = input[3][1] */
  wr43 = arg[3] ? arg[3]+19 : casadi_zeros;
  /* #149: @2 = @43[7] */
  w02 = wr43[7];
  /* #150: (@24[0] = @2) */
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #151: @2 = @43[8] */
  w02 = wr43[8];
  /* #152: (@24[9] = @2) */
  for (rr=w24+9, cs=(&w02); rr!=w24+10; rr+=1) *rr = *cs++;
  /* #153: @2 = @43[9] */
  w02 = wr43[9];
  /* #154: (@24[18] = @2) */
  for (rr=w24+18, cs=(&w02); rr!=w24+19; rr+=1) *rr = *cs++;
  /* #155: @2 = @43[10] */
  w02 = wr43[10];
  /* #156: (@24[27] = @2) */
  for (rr=w24+27, cs=(&w02); rr!=w24+28; rr+=1) *rr = *cs++;
  /* #157: @2 = @43[0] */
  w02 = wr43[0];
  /* #158: (@24[36] = @2) */
  for (rr=w24+36, cs=(&w02); rr!=w24+37; rr+=1) *rr = *cs++;
  /* #159: @2 = @43[1] */
  w02 = wr43[1];
  /* #160: (@24[45] = @2) */
  for (rr=w24+45, cs=(&w02); rr!=w24+46; rr+=1) *rr = *cs++;
  /* #161: @2 = @43[2] */
  w02 = wr43[2];
  /* #162: (@24[54] = @2) */
  for (rr=w24+54, cs=(&w02); rr!=w24+55; rr+=1) *rr = *cs++;
  /* #163: @2 = @43[3] */
  w02 = wr43[3];
  /* #164: (@24[63] = @2) */
  for (rr=w24+63, cs=(&w02); rr!=w24+64; rr+=1) *rr = *cs++;
  /* #165: @1 = mac(@35,@24,@1) */
  for (i=0, rr=w01; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w24+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #166: @0 = mac(@1,@5,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w05+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #167: @2 = 0 */
  w02 = 0.;
  /* #168: @36 = zeros(1x3) */
  casadi_clear(w36, 3);
  /* #169: @44 = @34[11:14] */
  for (rr=w44, cs=w34+11; cs!=w34+14; cs+=1) *rr++ = *cs;
  /* #170: @45 = @6[11:14] */
  wr45 = wr06+11;
  /* #171: @44 = (@44-@45) */
  for (i=0, rr=w44, cs=wr45; i<3; ++i) (*rr++) -= (*cs++);
  /* #172: @45 = @44' */
  casadi_copy(w44, 3, w45);
  /* #173: @46 = zeros(3x3) */
  casadi_clear(w46, 9);
  /* #174: @32 = @43[4] */
  w32 = wr43[4];
  /* #175: (@46[0] = @32) */
  for (rr=w46+0, cs=(&w32); rr!=w46+1; rr+=1) *rr = *cs++;
  /* #176: @32 = @43[5] */
  w32 = wr43[5];
  /* #177: (@46[4] = @32) */
  for (rr=w46+4, cs=(&w32); rr!=w46+5; rr+=1) *rr = *cs++;
  /* #178: @32 = @43[6] */
  w32 = wr43[6];
  /* #179: (@46[8] = @32) */
  for (rr=w46+8, cs=(&w32); rr!=w46+9; rr+=1) *rr = *cs++;
  /* #180: @36 = mac(@45,@46,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=w46+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #181: @2 = mac(@36,@44,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w44+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #182: @0 = (@0+@2) */
  w00 += w02;
  /* #183: @2 = 0 */
  w02 = 0.;
  /* #184: @45 = zeros(1x3) */
  casadi_clear(w45, 3);
  /* #185: @47 = @34[8:11] */
  for (rr=w47, cs=w34+8; cs!=w34+11; cs+=1) *rr++ = *cs;
  /* #186: @48 = @6[8:11] */
  wr48 = wr06+8;
  /* #187: @47 = (@47-@48) */
  for (i=0, rr=w47, cs=wr48; i<3; ++i) (*rr++) -= (*cs++);
  /* #188: @48 = @47' */
  casadi_copy(w47, 3, w48);
  /* #189: @49 = zeros(3x3) */
  casadi_clear(w49, 9);
  /* #190: @32 = @43[11] */
  w32 = wr43[11];
  /* #191: (@49[0] = @32) */
  for (rr=w49+0, cs=(&w32); rr!=w49+1; rr+=1) *rr = *cs++;
  /* #192: @32 = @43[12] */
  w32 = wr43[12];
  /* #193: (@49[4] = @32) */
  for (rr=w49+4, cs=(&w32); rr!=w49+5; rr+=1) *rr = *cs++;
  /* #194: @32 = @43[13] */
  w32 = wr43[13];
  /* #195: (@49[8] = @32) */
  for (rr=w49+8, cs=(&w32); rr!=w49+9; rr+=1) *rr = *cs++;
  /* #196: @45 = mac(@48,@49,@45) */
  for (i=0, rr=w45; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w48+j, ct=w49+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #197: @2 = mac(@45,@47,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=w47+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #198: @0 = (@0+@2) */
  w00 += w02;
  /* #199: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #200: @34 = zeros(15x1) */
  casadi_clear(w34, 15);
  /* #201: @45 = @45' */
  /* #202: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #203: @47 = @47' */
  /* #204: @50 = @49' */
  for (i=0, rr=w50, cs=w49; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #205: @48 = mac(@47,@50,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w50+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #206: @48 = @48' */
  /* #207: @45 = (@45+@48) */
  for (i=0, rr=w45, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #208: (@34[8:11] += @45) */
  for (rr=w34+8, cs=w45; rr!=w34+11; rr+=1) *rr += *cs++;
  /* #209: @36 = @36' */
  /* #210: @45 = zeros(1x3) */
  casadi_clear(w45, 3);
  /* #211: @44 = @44' */
  /* #212: @50 = @46' */
  for (i=0, rr=w50, cs=w46; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #213: @45 = mac(@44,@50,@45) */
  for (i=0, rr=w45; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w44+j, ct=w50+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #214: @45 = @45' */
  /* #215: @36 = (@36+@45) */
  for (i=0, rr=w36, cs=w45; i<3; ++i) (*rr++) += (*cs++);
  /* #216: (@34[11:14] += @36) */
  for (rr=w34+11, cs=w36; rr!=w34+14; rr+=1) *rr += *cs++;
  /* #217: @35 = zeros(8x1) */
  casadi_clear(w35, 8);
  /* #218: @51 = zeros(8x1) */
  casadi_clear(w51, 8);
  /* #219: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #220: @21 = @18' */
  for (i=0, rr=w21, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #221: @15 = zeros(4x1) */
  casadi_clear(w15, 4);
  /* #222: @1 = @1' */
  /* #223: @52 = zeros(1x8) */
  casadi_clear(w52, 8);
  /* #224: @5 = @5' */
  /* #225: @53 = @24' */
  for (i=0, rr=w53, cs=w24; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #226: @52 = mac(@5,@53,@52) */
  for (i=0, rr=w52; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w05+j, ct=w53+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #227: @52 = @52' */
  /* #228: @1 = (@1+@52) */
  for (i=0, rr=w01, cs=w52; i<8; ++i) (*rr++) += (*cs++);
  /* #229: {NULL, @0, @2, @32, NULL, @37, @39, @42} = vertsplit(@1) */
  w00 = w01[1];
  w02 = w01[2];
  w32 = w01[3];
  w37 = w01[5];
  w39 = w01[6];
  w42 = w01[7];
  /* #230: @40 = (@40*@42) */
  w40 *= w42;
  /* #231: (@15[3] += @40) */
  for (rr=w15+3, cs=(&w40); rr!=w15+4; rr+=1) *rr += *cs++;
  /* #232: @38 = (@38*@39) */
  w38 *= w39;
  /* #233: (@15[2] += @38) */
  for (rr=w15+2, cs=(&w38); rr!=w15+3; rr+=1) *rr += *cs++;
  /* #234: @33 = (@33*@37) */
  w33 *= w37;
  /* #235: (@15[1] += @33) */
  for (rr=w15+1, cs=(&w33); rr!=w15+2; rr+=1) *rr += *cs++;
  /* #236: @11 = mac(@21,@15,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w21+j, ct=w15+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #237: {@33, @37, @38, @39} = vertsplit(@11) */
  w33 = w11[0];
  w37 = w11[1];
  w38 = w11[2];
  w39 = w11[3];
  /* #238: @39 = (-@39) */
  w39 = (- w39 );
  /* #239: (@51[3] += @39) */
  for (rr=w51+3, cs=(&w39); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #240: @38 = (-@38) */
  w38 = (- w38 );
  /* #241: (@51[2] += @38) */
  for (rr=w51+2, cs=(&w38); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #242: @37 = (-@37) */
  w37 = (- w37 );
  /* #243: (@51[1] += @37) */
  for (rr=w51+1, cs=(&w37); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #244: (@51[0] += @33) */
  for (rr=w51+0, cs=(&w33); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #245: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #246: @14 = @14' */
  /* #247: @21 = mac(@15,@14,@21) */
  for (i=0, rr=w21; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w15+j, ct=w14+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #248: @21 = (2.*@21) */
  for (i=0, rr=w21, cs=w21; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #249: @18 = @21' */
  for (i=0, rr=w18, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #250: {@15, @14, @11, @16} = horzsplit(@18) */
  casadi_copy(w18, 4, w15);
  casadi_copy(w18+4, 4, w14);
  casadi_copy(w18+8, 4, w11);
  casadi_copy(w18+12, 4, w16);
  /* #251: @16 = @16' */
  /* #252: {@33, @37, @38, @39} = horzsplit(@16) */
  w33 = w16[0];
  w37 = w16[1];
  w38 = w16[2];
  w39 = w16[3];
  /* #253: (@51[4] += @39) */
  for (rr=w51+4, cs=(&w39); rr!=w51+5; rr+=1) *rr += *cs++;
  /* #254: (@51[5] += @38) */
  for (rr=w51+5, cs=(&w38); rr!=w51+6; rr+=1) *rr += *cs++;
  /* #255: @37 = (-@37) */
  w37 = (- w37 );
  /* #256: (@51[6] += @37) */
  for (rr=w51+6, cs=(&w37); rr!=w51+7; rr+=1) *rr += *cs++;
  /* #257: (@51[7] += @33) */
  for (rr=w51+7, cs=(&w33); rr!=w51+8; rr+=1) *rr += *cs++;
  /* #258: @11 = @11' */
  /* #259: {@33, @37, @38, @39} = horzsplit(@11) */
  w33 = w11[0];
  w37 = w11[1];
  w38 = w11[2];
  w39 = w11[3];
  /* #260: @39 = (-@39) */
  w39 = (- w39 );
  /* #261: (@51[5] += @39) */
  for (rr=w51+5, cs=(&w39); rr!=w51+6; rr+=1) *rr += *cs++;
  /* #262: (@51[4] += @38) */
  for (rr=w51+4, cs=(&w38); rr!=w51+5; rr+=1) *rr += *cs++;
  /* #263: (@51[7] += @37) */
  for (rr=w51+7, cs=(&w37); rr!=w51+8; rr+=1) *rr += *cs++;
  /* #264: (@51[6] += @33) */
  for (rr=w51+6, cs=(&w33); rr!=w51+7; rr+=1) *rr += *cs++;
  /* #265: @14 = @14' */
  /* #266: {@33, @37, @38, @39} = horzsplit(@14) */
  w33 = w14[0];
  w37 = w14[1];
  w38 = w14[2];
  w39 = w14[3];
  /* #267: (@51[6] += @39) */
  for (rr=w51+6, cs=(&w39); rr!=w51+7; rr+=1) *rr += *cs++;
  /* #268: @38 = (-@38) */
  w38 = (- w38 );
  /* #269: (@51[7] += @38) */
  for (rr=w51+7, cs=(&w38); rr!=w51+8; rr+=1) *rr += *cs++;
  /* #270: (@51[4] += @37) */
  for (rr=w51+4, cs=(&w37); rr!=w51+5; rr+=1) *rr += *cs++;
  /* #271: (@51[5] += @33) */
  for (rr=w51+5, cs=(&w33); rr!=w51+6; rr+=1) *rr += *cs++;
  /* #272: @15 = @15' */
  /* #273: {@33, @37, @38, @39} = horzsplit(@15) */
  w33 = w15[0];
  w37 = w15[1];
  w38 = w15[2];
  w39 = w15[3];
  /* #274: @39 = (-@39) */
  w39 = (- w39 );
  /* #275: (@51[7] += @39) */
  for (rr=w51+7, cs=(&w39); rr!=w51+8; rr+=1) *rr += *cs++;
  /* #276: @38 = (-@38) */
  w38 = (- w38 );
  /* #277: (@51[6] += @38) */
  for (rr=w51+6, cs=(&w38); rr!=w51+7; rr+=1) *rr += *cs++;
  /* #278: @37 = (-@37) */
  w37 = (- w37 );
  /* #279: (@51[5] += @37) */
  for (rr=w51+5, cs=(&w37); rr!=w51+6; rr+=1) *rr += *cs++;
  /* #280: (@51[4] += @33) */
  for (rr=w51+4, cs=(&w33); rr!=w51+5; rr+=1) *rr += *cs++;
  /* #281: @33 = (@32/@13) */
  w33  = (w32/w13);
  /* #282: @10 = (@10*@33) */
  w10 *= w33;
  /* #283: (@51[3] += @10) */
  for (rr=w51+3, cs=(&w10); rr!=w51+4; rr+=1) *rr += *cs++;
  /* #284: @10 = (@2/@13) */
  w10  = (w02/w13);
  /* #285: @26 = (@26*@10) */
  w26 *= w10;
  /* #286: (@51[2] += @26) */
  for (rr=w51+2, cs=(&w26); rr!=w51+3; rr+=1) *rr += *cs++;
  /* #287: @26 = (@0/@13) */
  w26  = (w00/w13);
  /* #288: @8 = (@8*@26) */
  w08 *= w26;
  /* #289: (@51[1] += @8) */
  for (rr=w51+1, cs=(&w08); rr!=w51+2; rr+=1) *rr += *cs++;
  /* #290: @8 = sq(@13) */
  w08 = casadi_sq( w13 );
  /* #291: @37 = sq(@7) */
  w37 = casadi_sq( w07 );
  /* #292: @8 = (@8+@37) */
  w08 += w37;
  /* #293: @37 = (@13/@8) */
  w37  = (w13/w08);
  /* #294: @30 = (@30*@33) */
  w30 *= w33;
  /* #295: @29 = (@29*@30) */
  w29 *= w30;
  /* #296: @27 = (@27*@10) */
  w27 *= w10;
  /* #297: @25 = (@25*@27) */
  w25 *= w27;
  /* #298: @29 = (@29+@25) */
  w29 += w25;
  /* #299: @12 = (@12*@26) */
  w12 *= w26;
  /* #300: @3 = (@3*@12) */
  w03 *= w12;
  /* #301: @29 = (@29+@3) */
  w29 += w03;
  /* #302: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #303: @37 = (@37*@29) */
  w37 *= w29;
  /* #304: @37 = (-@37) */
  w37 = (- w37 );
  /* #305: (@51[0] += @37) */
  for (rr=w51+0, cs=(&w37); rr!=w51+1; rr+=1) *rr += *cs++;
  /* #306: @28 = (@28/@13) */
  w28 /= w13;
  /* #307: @28 = (@28*@2) */
  w28 *= w02;
  /* #308: @28 = (-@28) */
  w28 = (- w28 );
  /* #309: @31 = (@31/@13) */
  w31 /= w13;
  /* #310: @31 = (@31*@32) */
  w31 *= w32;
  /* #311: @28 = (@28-@31) */
  w28 -= w31;
  /* #312: @9 = (@9/@13) */
  w09 /= w13;
  /* #313: @9 = (@9*@0) */
  w09 *= w00;
  /* #314: @28 = (@28-@9) */
  w28 -= w09;
  /* #315: @7 = (@7/@8) */
  w07 /= w08;
  /* #316: @7 = (@7*@29) */
  w07 *= w29;
  /* #317: @28 = (@28+@7) */
  w28 += w07;
  /* #318: @28 = (@28/@13) */
  w28 /= w13;
  /* #319: @4 = (@28*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w28*(*cs++));
  /* #320: (@51[1:4] += @4) */
  for (rr=w51+1, cs=w04; rr!=w51+4; rr+=1) *rr += *cs++;
  /* #321: @35 = mac(@23,@51,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w23+j, ct=w51+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #322: (@34[:8] += @35) */
  for (rr=w34+0, cs=w35; rr!=w34+8; rr+=1) *rr += *cs++;
  /* #323: output[1][0] = @34 */
  casadi_copy(w34, 15, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 540;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 10*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 540*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
