/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {0, 0, 1};
static const casadi_int casadi_s2[3] = {53, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_zeros[34] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* quadrotor_cost_ext_cost_e_fun:(i0[15],i1[],i2[],i3[53])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+9, w02, w03, *w04=w+19, *w05=w+22, w07, w08, w09, w10, *w11=w+53;
  casadi_real w12, w13, *w14=w+59, *w15=w+63, *w16=w+67, *w17=w+71, *w18=w+87, *w19=w+103, *w20=w+135, *w21=w+167, *w22=w+183, *w23=w+215;
  casadi_real *w24=w+279, w25, w26, w27, w28, w29, w30, w31, w32, w33, *w34=w+352, *w35=w+367;
  casadi_real *w36=w+375, *w37=w+378, *w39=w+416, *w40=w+419;
  const casadi_real *cs, *ct, *wr06, *wr38, *wr39;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w01, 8);
  /* #2: @2 = 0 */
  w02 = 0.;
  /* #3: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #4: @4 = all_2.22045e-16(3x1) */
  casadi_fill(w04, 3, 2.2204460492503131e-16);
  /* #5: @5 = zeros(8x1) */
  casadi_clear(w05, 8);
  /* #6: @6 = input[3][0] */
  wr06 = arg[3] ? arg[3] : casadi_zeros;
  /* #7: @7 = @6[0] */
  w07 = wr06[0];
  /* #8: @8 = @6[1] */
  w08 = wr06[1];
  /* #9: @9 = @6[2] */
  w09 = wr06[2];
  /* #10: @10 = @6[3] */
  w10 = wr06[3];
  /* #11: @11 = horzcat(@7, @8, @9, @10) */
  rr=w11;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  /* #12: @11 = @11' */
  /* #13: @7 = (-@8) */
  w07 = (- w08 );
  /* #14: @12 = @6[0] */
  w12 = wr06[0];
  /* #15: @13 = (-@9) */
  w13 = (- w09 );
  /* #16: @14 = horzcat(@7, @12, @10, @13) */
  rr=w14;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w13;
  /* #17: @14 = @14' */
  /* #18: @10 = (-@10) */
  w10 = (- w10 );
  /* #19: @12 = @6[0] */
  w12 = wr06[0];
  /* #20: @15 = horzcat(@13, @10, @12, @8) */
  rr=w15;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w08;
  /* #21: @15 = @15' */
  /* #22: @13 = @6[0] */
  w13 = wr06[0];
  /* #23: @16 = horzcat(@10, @9, @7, @13) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w13;
  /* #24: @16 = @16' */
  /* #25: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #26: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #27: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #28: @19 = horzcat(@18, @17) */
  rr=w19;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #29: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #30: @10 = @6[4] */
  w10 = wr06[4];
  /* #31: @9 = @6[5] */
  w09 = wr06[5];
  /* #32: @7 = @6[6] */
  w07 = wr06[6];
  /* #33: @13 = @6[7] */
  w13 = wr06[7];
  /* #34: @11 = horzcat(@10, @9, @7, @13) */
  rr=w11;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w13;
  /* #35: @11 = @11' */
  /* #36: @10 = (-@9) */
  w10 = (- w09 );
  /* #37: @12 = @6[4] */
  w12 = wr06[4];
  /* #38: @8 = (-@7) */
  w08 = (- w07 );
  /* #39: @14 = horzcat(@10, @12, @13, @8) */
  rr=w14;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w08;
  /* #40: @14 = @14' */
  /* #41: @13 = (-@13) */
  w13 = (- w13 );
  /* #42: @12 = @6[4] */
  w12 = wr06[4];
  /* #43: @15 = horzcat(@8, @13, @12, @9) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w09;
  /* #44: @15 = @15' */
  /* #45: @8 = @6[4] */
  w08 = wr06[4];
  /* #46: @16 = horzcat(@13, @7, @10, @8) */
  rr=w16;
  *rr++ = w13;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w08;
  /* #47: @16 = @16' */
  /* #48: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #49: @21 = @17' */
  for (i=0, rr=w21, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #50: @19 = horzcat(@21, @18) */
  rr=w19;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #51: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #52: @23 = horzcat(@20, @22) */
  rr=w23;
  for (i=0, cs=w20; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  /* #53: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #54: @13 = input[0][0] */
  w13 = arg[0] ? arg[0][0] : 0;
  /* #55: @7 = input[0][1] */
  w07 = arg[0] ? arg[0][1] : 0;
  /* #56: @10 = input[0][2] */
  w10 = arg[0] ? arg[0][2] : 0;
  /* #57: @8 = input[0][3] */
  w08 = arg[0] ? arg[0][3] : 0;
  /* #58: @12 = input[0][4] */
  w12 = arg[0] ? arg[0][4] : 0;
  /* #59: @9 = input[0][5] */
  w09 = arg[0] ? arg[0][5] : 0;
  /* #60: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #61: @26 = input[0][7] */
  w26 = arg[0] ? arg[0][7] : 0;
  /* #62: @27 = input[0][8] */
  w27 = arg[0] ? arg[0][8] : 0;
  /* #63: @28 = input[0][9] */
  w28 = arg[0] ? arg[0][9] : 0;
  /* #64: @29 = input[0][10] */
  w29 = arg[0] ? arg[0][10] : 0;
  /* #65: @30 = input[0][11] */
  w30 = arg[0] ? arg[0][11] : 0;
  /* #66: @31 = input[0][12] */
  w31 = arg[0] ? arg[0][12] : 0;
  /* #67: @32 = input[0][13] */
  w32 = arg[0] ? arg[0][13] : 0;
  /* #68: @33 = input[0][14] */
  w33 = arg[0] ? arg[0][14] : 0;
  /* #69: @34 = vertcat(@13, @7, @10, @8, @12, @9, @25, @26, @27, @28, @29, @30, @31, @32, @33) */
  rr=w34;
  *rr++ = w13;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  /* #70: @35 = @34[:8] */
  for (rr=w35, cs=w34+0; cs!=w34+8; cs+=1) *rr++ = *cs;
  /* #71: @5 = mac(@24,@35,@5) */
  for (i=0, rr=w05; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w24+j, ct=w35+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #72: @36 = @5[1:4] */
  for (rr=w36, cs=w05+1; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #73: @4 = (@4+@36) */
  for (i=0, rr=w04, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #74: @13 = ||@4||_F */
  w13 = casadi_norm_2(3, w04);
  /* #75: @7 = @5[0] */
  for (rr=(&w07), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #76: @7 = atan2(@13,@7) */
  w07  = atan2(w13,w07);
  /* #77: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #78: @3 = (@3*@7) */
  w03 *= w07;
  /* #79: @10 = @5[1] */
  for (rr=(&w10), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #80: @3 = (@3*@10) */
  w03 *= w10;
  /* #81: @3 = (@3/@13) */
  w03 /= w13;
  /* #82: @10 = 0.5 */
  w10 = 5.0000000000000000e-01;
  /* #83: @10 = (@10*@7) */
  w10 *= w07;
  /* #84: @8 = @5[2] */
  for (rr=(&w08), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #85: @10 = (@10*@8) */
  w10 *= w08;
  /* #86: @10 = (@10/@13) */
  w10 /= w13;
  /* #87: @8 = 0.5 */
  w08 = 5.0000000000000000e-01;
  /* #88: @8 = (@8*@7) */
  w08 *= w07;
  /* #89: @7 = @5[3] */
  for (rr=(&w07), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #90: @8 = (@8*@7) */
  w08 *= w07;
  /* #91: @8 = (@8/@13) */
  w08 /= w13;
  /* #92: @13 = 0 */
  w13 = 0.;
  /* #93: @7 = 0.5 */
  w07 = 5.0000000000000000e-01;
  /* #94: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #95: @12 = @5[4] */
  for (rr=(&w12), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #96: @9 = @5[5] */
  for (rr=(&w09), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #97: @9 = (-@9) */
  w09 = (- w09 );
  /* #98: @25 = @5[6] */
  for (rr=(&w25), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #99: @25 = (-@25) */
  w25 = (- w25 );
  /* #100: @26 = @5[7] */
  for (rr=(&w26), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #101: @26 = (-@26) */
  w26 = (- w26 );
  /* #102: @14 = horzcat(@12, @9, @25, @26) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w25;
  *rr++ = w26;
  /* #103: @14 = @14' */
  /* #104: @12 = @5[5] */
  for (rr=(&w12), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #105: @9 = @5[4] */
  for (rr=(&w09), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #106: @25 = @5[7] */
  for (rr=(&w25), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #107: @25 = (-@25) */
  w25 = (- w25 );
  /* #108: @26 = @5[6] */
  for (rr=(&w26), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #109: @15 = horzcat(@12, @9, @25, @26) */
  rr=w15;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w25;
  *rr++ = w26;
  /* #110: @15 = @15' */
  /* #111: @12 = @5[6] */
  for (rr=(&w12), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #112: @9 = @5[7] */
  for (rr=(&w09), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #113: @25 = @5[4] */
  for (rr=(&w25), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #114: @26 = @5[5] */
  for (rr=(&w26), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #115: @26 = (-@26) */
  w26 = (- w26 );
  /* #116: @16 = horzcat(@12, @9, @25, @26) */
  rr=w16;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w25;
  *rr++ = w26;
  /* #117: @16 = @16' */
  /* #118: @12 = @5[7] */
  for (rr=(&w12), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #119: @9 = @5[6] */
  for (rr=(&w09), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #120: @9 = (-@9) */
  w09 = (- w09 );
  /* #121: @25 = @5[5] */
  for (rr=(&w25), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #122: @26 = @5[4] */
  for (rr=(&w26), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #123: @37 = horzcat(@12, @9, @25, @26) */
  rr=w37;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w25;
  *rr++ = w26;
  /* #124: @37 = @37' */
  /* #125: @21 = horzcat(@14, @15, @16, @37) */
  rr=w21;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<4; ++i) *rr++ = *cs++;
  /* #126: @18 = @21' */
  for (i=0, rr=w18, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #127: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #128: @12 = @5[0] */
  for (rr=(&w12), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #129: @9 = @5[1] */
  for (rr=(&w09), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #130: @9 = (-@9) */
  w09 = (- w09 );
  /* #131: @25 = @5[2] */
  for (rr=(&w25), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #132: @25 = (-@25) */
  w25 = (- w25 );
  /* #133: @26 = @5[3] */
  for (rr=(&w26), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #134: @26 = (-@26) */
  w26 = (- w26 );
  /* #135: @14 = vertcat(@12, @9, @25, @26) */
  rr=w14;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w25;
  *rr++ = w26;
  /* #136: @11 = mac(@18,@14,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w18+j, ct=w14+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #137: @12 = @11[1] */
  for (rr=(&w12), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #138: @7 = (@7*@12) */
  w07 *= w12;
  /* #139: @12 = 0.5 */
  w12 = 5.0000000000000000e-01;
  /* #140: @9 = @11[2] */
  for (rr=(&w09), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #141: @12 = (@12*@9) */
  w12 *= w09;
  /* #142: @9 = 0.5 */
  w09 = 5.0000000000000000e-01;
  /* #143: @25 = @11[3] */
  for (rr=(&w25), cs=w11+3; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #144: @9 = (@9*@25) */
  w09 *= w25;
  /* #145: @5 = vertcat(@2, @3, @10, @8, @13, @7, @12, @9) */
  rr=w05;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w09;
  /* #146: @35 = @5' */
  casadi_copy(w05, 8, w35);
  /* #147: @24 = zeros(8x8) */
  casadi_clear(w24, 64);
  /* #148: @38 = input[3][1] */
  wr38 = arg[3] ? arg[3]+19 : casadi_zeros;
  /* #149: @2 = @38[7] */
  w02 = wr38[7];
  /* #150: (@24[0] = @2) */
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #151: @2 = @38[8] */
  w02 = wr38[8];
  /* #152: (@24[9] = @2) */
  for (rr=w24+9, cs=(&w02); rr!=w24+10; rr+=1) *rr = *cs++;
  /* #153: @2 = @38[9] */
  w02 = wr38[9];
  /* #154: (@24[18] = @2) */
  for (rr=w24+18, cs=(&w02); rr!=w24+19; rr+=1) *rr = *cs++;
  /* #155: @2 = @38[10] */
  w02 = wr38[10];
  /* #156: (@24[27] = @2) */
  for (rr=w24+27, cs=(&w02); rr!=w24+28; rr+=1) *rr = *cs++;
  /* #157: @2 = @38[0] */
  w02 = wr38[0];
  /* #158: (@24[36] = @2) */
  for (rr=w24+36, cs=(&w02); rr!=w24+37; rr+=1) *rr = *cs++;
  /* #159: @2 = @38[1] */
  w02 = wr38[1];
  /* #160: (@24[45] = @2) */
  for (rr=w24+45, cs=(&w02); rr!=w24+46; rr+=1) *rr = *cs++;
  /* #161: @2 = @38[2] */
  w02 = wr38[2];
  /* #162: (@24[54] = @2) */
  for (rr=w24+54, cs=(&w02); rr!=w24+55; rr+=1) *rr = *cs++;
  /* #163: @2 = @38[3] */
  w02 = wr38[3];
  /* #164: (@24[63] = @2) */
  for (rr=w24+63, cs=(&w02); rr!=w24+64; rr+=1) *rr = *cs++;
  /* #165: @1 = mac(@35,@24,@1) */
  for (i=0, rr=w01; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w24+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #166: @0 = mac(@1,@5,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w05+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #167: @2 = 0 */
  w02 = 0.;
  /* #168: @4 = zeros(1x3) */
  casadi_clear(w04, 3);
  /* #169: @36 = @34[11:14] */
  for (rr=w36, cs=w34+11; cs!=w34+14; cs+=1) *rr++ = *cs;
  /* #170: @39 = @6[11:14] */
  wr39 = wr06+11;
  /* #171: @36 = (@36-@39) */
  for (i=0, rr=w36, cs=wr39; i<3; ++i) (*rr++) -= (*cs++);
  /* #172: @39 = @36' */
  casadi_copy(w36, 3, w39);
  /* #173: @40 = zeros(3x3) */
  casadi_clear(w40, 9);
  /* #174: @3 = @38[4] */
  w03 = wr38[4];
  /* #175: (@40[0] = @3) */
  for (rr=w40+0, cs=(&w03); rr!=w40+1; rr+=1) *rr = *cs++;
  /* #176: @3 = @38[5] */
  w03 = wr38[5];
  /* #177: (@40[4] = @3) */
  for (rr=w40+4, cs=(&w03); rr!=w40+5; rr+=1) *rr = *cs++;
  /* #178: @3 = @38[6] */
  w03 = wr38[6];
  /* #179: (@40[8] = @3) */
  for (rr=w40+8, cs=(&w03); rr!=w40+9; rr+=1) *rr = *cs++;
  /* #180: @4 = mac(@39,@40,@4) */
  for (i=0, rr=w04; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w39+j, ct=w40+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #181: @2 = mac(@4,@36,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #182: @0 = (@0+@2) */
  w00 += w02;
  /* #183: @2 = 0 */
  w02 = 0.;
  /* #184: @4 = zeros(1x3) */
  casadi_clear(w04, 3);
  /* #185: @36 = @34[8:11] */
  for (rr=w36, cs=w34+8; cs!=w34+11; cs+=1) *rr++ = *cs;
  /* #186: @39 = @6[8:11] */
  wr39 = wr06+8;
  /* #187: @36 = (@36-@39) */
  for (i=0, rr=w36, cs=wr39; i<3; ++i) (*rr++) -= (*cs++);
  /* #188: @39 = @36' */
  casadi_copy(w36, 3, w39);
  /* #189: @40 = zeros(3x3) */
  casadi_clear(w40, 9);
  /* #190: @3 = @38[11] */
  w03 = wr38[11];
  /* #191: (@40[0] = @3) */
  for (rr=w40+0, cs=(&w03); rr!=w40+1; rr+=1) *rr = *cs++;
  /* #192: @3 = @38[12] */
  w03 = wr38[12];
  /* #193: (@40[4] = @3) */
  for (rr=w40+4, cs=(&w03); rr!=w40+5; rr+=1) *rr = *cs++;
  /* #194: @3 = @38[13] */
  w03 = wr38[13];
  /* #195: (@40[8] = @3) */
  for (rr=w40+8, cs=(&w03); rr!=w40+9; rr+=1) *rr = *cs++;
  /* #196: @4 = mac(@39,@40,@4) */
  for (i=0, rr=w04; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w39+j, ct=w40+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #197: @2 = mac(@4,@36,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w04+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #198: @0 = (@0+@2) */
  w00 += w02;
  /* #199: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 428;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 428*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
