/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {50, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {18, 1, 1};

static const casadi_real casadi_zeros[32] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* quadrotor_cost_ext_cost_0_fun_jac:(i0[14],i1[4],i2[],i3[50])->(o0,o1[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+9, w02, w03, *w04=w+19, *w05=w+22, w07, w08, w09, w10, *w11=w+52;
  casadi_real w12, w13, *w14=w+58, *w15=w+62, *w16=w+66, *w17=w+70, *w18=w+86, *w19=w+102, *w20=w+134, *w21=w+166, *w22=w+182, *w23=w+214;
  casadi_real *w24=w+278, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+350, *w34=w+364, *w35=w+372;
  casadi_real w36, w37, w38, w39, w40, *w41=w+380, w42, *w43=w+385, *w44=w+388, *w45=w+391, *w46=w+400, *w47=w+403;
  casadi_real *w48=w+406, *w49=w+415, *w50=w+424, *w51=w+432, *w52=w+440;
  const casadi_real *cr, *cs, *ct, *wr06, *wr15, *wr20, *wr41, *wr44, *wr47;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w01, 8);
  /* #2: @2 = 0 */
  w02 = 0.;
  /* #3: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #4: @4 = all_2.22045e-16(3x1) */
  casadi_fill(w04, 3, 2.2204460492503131e-16);
  /* #5: @5 = zeros(8x1) */
  casadi_clear(w05, 8);
  /* #6: @6 = input[3][0] */
  wr06 = arg[3] ? arg[3] : casadi_zeros;
  /* #7: @7 = @6[0] */
  w07 = wr06[0];
  /* #8: @8 = @6[1] */
  w08 = wr06[1];
  /* #9: @9 = @6[2] */
  w09 = wr06[2];
  /* #10: @10 = @6[3] */
  w10 = wr06[3];
  /* #11: @11 = horzcat(@7, @8, @9, @10) */
  rr=w11;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  /* #12: @11 = @11' */
  /* #13: @7 = (-@8) */
  w07 = (- w08 );
  /* #14: @12 = @6[0] */
  w12 = wr06[0];
  /* #15: @13 = (-@9) */
  w13 = (- w09 );
  /* #16: @14 = horzcat(@7, @12, @10, @13) */
  rr=w14;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w13;
  /* #17: @14 = @14' */
  /* #18: @10 = (-@10) */
  w10 = (- w10 );
  /* #19: @12 = @6[0] */
  w12 = wr06[0];
  /* #20: @15 = horzcat(@13, @10, @12, @8) */
  rr=w15;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w08;
  /* #21: @15 = @15' */
  /* #22: @13 = @6[0] */
  w13 = wr06[0];
  /* #23: @16 = horzcat(@10, @9, @7, @13) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w13;
  /* #24: @16 = @16' */
  /* #25: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #26: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #27: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #28: @19 = horzcat(@18, @17) */
  rr=w19;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #29: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #30: @10 = @6[4] */
  w10 = wr06[4];
  /* #31: @9 = @6[5] */
  w09 = wr06[5];
  /* #32: @7 = @6[6] */
  w07 = wr06[6];
  /* #33: @13 = @6[7] */
  w13 = wr06[7];
  /* #34: @11 = horzcat(@10, @9, @7, @13) */
  rr=w11;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w13;
  /* #35: @11 = @11' */
  /* #36: @10 = (-@9) */
  w10 = (- w09 );
  /* #37: @12 = @6[4] */
  w12 = wr06[4];
  /* #38: @8 = (-@7) */
  w08 = (- w07 );
  /* #39: @14 = horzcat(@10, @12, @13, @8) */
  rr=w14;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w08;
  /* #40: @14 = @14' */
  /* #41: @13 = (-@13) */
  w13 = (- w13 );
  /* #42: @12 = @6[4] */
  w12 = wr06[4];
  /* #43: @15 = horzcat(@8, @13, @12, @9) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w09;
  /* #44: @15 = @15' */
  /* #45: @8 = @6[4] */
  w08 = wr06[4];
  /* #46: @16 = horzcat(@13, @7, @10, @8) */
  rr=w16;
  *rr++ = w13;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w08;
  /* #47: @16 = @16' */
  /* #48: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #49: @21 = @17' */
  for (i=0, rr=w21, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #50: @19 = horzcat(@21, @18) */
  rr=w19;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #51: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #52: @23 = horzcat(@20, @22) */
  rr=w23;
  for (i=0, cs=w20; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  /* #53: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #54: @13 = input[0][0] */
  w13 = arg[0] ? arg[0][0] : 0;
  /* #55: @7 = input[0][1] */
  w07 = arg[0] ? arg[0][1] : 0;
  /* #56: @10 = input[0][2] */
  w10 = arg[0] ? arg[0][2] : 0;
  /* #57: @8 = input[0][3] */
  w08 = arg[0] ? arg[0][3] : 0;
  /* #58: @12 = input[0][4] */
  w12 = arg[0] ? arg[0][4] : 0;
  /* #59: @9 = input[0][5] */
  w09 = arg[0] ? arg[0][5] : 0;
  /* #60: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #61: @26 = input[0][7] */
  w26 = arg[0] ? arg[0][7] : 0;
  /* #62: @27 = input[0][8] */
  w27 = arg[0] ? arg[0][8] : 0;
  /* #63: @28 = input[0][9] */
  w28 = arg[0] ? arg[0][9] : 0;
  /* #64: @29 = input[0][10] */
  w29 = arg[0] ? arg[0][10] : 0;
  /* #65: @30 = input[0][11] */
  w30 = arg[0] ? arg[0][11] : 0;
  /* #66: @31 = input[0][12] */
  w31 = arg[0] ? arg[0][12] : 0;
  /* #67: @32 = input[0][13] */
  w32 = arg[0] ? arg[0][13] : 0;
  /* #68: @33 = vertcat(@13, @7, @10, @8, @12, @9, @25, @26, @27, @28, @29, @30, @31, @32) */
  rr=w33;
  *rr++ = w13;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #69: @34 = @33[:8] */
  for (rr=w34, cs=w33+0; cs!=w33+8; cs+=1) *rr++ = *cs;
  /* #70: @5 = mac(@24,@34,@5) */
  for (i=0, rr=w05; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w24+j, ct=w34+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #71: @35 = @5[1:4] */
  for (rr=w35, cs=w05+1; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #72: @4 = (@4+@35) */
  for (i=0, rr=w04, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #73: @13 = ||@4||_F */
  w13 = casadi_norm_2(3, w04);
  /* #74: @7 = @5[0] */
  for (rr=(&w07), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #75: @10 = atan2(@13,@7) */
  w10  = atan2(w13,w07);
  /* #76: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #77: @8 = (@3*@10) */
  w08  = (w03*w10);
  /* #78: @12 = @5[1] */
  for (rr=(&w12), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #79: @9 = (@8*@12) */
  w09  = (w08*w12);
  /* #80: @9 = (@9/@13) */
  w09 /= w13;
  /* #81: @25 = 0.5 */
  w25 = 5.0000000000000000e-01;
  /* #82: @26 = (@25*@10) */
  w26  = (w25*w10);
  /* #83: @27 = @5[2] */
  for (rr=(&w27), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #84: @28 = (@26*@27) */
  w28  = (w26*w27);
  /* #85: @28 = (@28/@13) */
  w28 /= w13;
  /* #86: @29 = 0.5 */
  w29 = 5.0000000000000000e-01;
  /* #87: @10 = (@29*@10) */
  w10  = (w29*w10);
  /* #88: @30 = @5[3] */
  for (rr=(&w30), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #89: @31 = (@10*@30) */
  w31  = (w10*w30);
  /* #90: @31 = (@31/@13) */
  w31 /= w13;
  /* #91: @32 = 0 */
  w32 = 0.;
  /* #92: @36 = 0.5 */
  w36 = 5.0000000000000000e-01;
  /* #93: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #94: @37 = @5[4] */
  for (rr=(&w37), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #95: @38 = @5[5] */
  for (rr=(&w38), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #96: @38 = (-@38) */
  w38 = (- w38 );
  /* #97: @39 = @5[6] */
  for (rr=(&w39), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #98: @39 = (-@39) */
  w39 = (- w39 );
  /* #99: @40 = @5[7] */
  for (rr=(&w40), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #100: @40 = (-@40) */
  w40 = (- w40 );
  /* #101: @14 = horzcat(@37, @38, @39, @40) */
  rr=w14;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #102: @14 = @14' */
  /* #103: @37 = @5[5] */
  for (rr=(&w37), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #104: @38 = @5[4] */
  for (rr=(&w38), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #105: @39 = @5[7] */
  for (rr=(&w39), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #106: @39 = (-@39) */
  w39 = (- w39 );
  /* #107: @40 = @5[6] */
  for (rr=(&w40), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #108: @15 = horzcat(@37, @38, @39, @40) */
  rr=w15;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #109: @15 = @15' */
  /* #110: @37 = @5[6] */
  for (rr=(&w37), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #111: @38 = @5[7] */
  for (rr=(&w38), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #112: @39 = @5[4] */
  for (rr=(&w39), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #113: @40 = @5[5] */
  for (rr=(&w40), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #114: @40 = (-@40) */
  w40 = (- w40 );
  /* #115: @16 = horzcat(@37, @38, @39, @40) */
  rr=w16;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #116: @16 = @16' */
  /* #117: @37 = @5[7] */
  for (rr=(&w37), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #118: @38 = @5[6] */
  for (rr=(&w38), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #119: @38 = (-@38) */
  w38 = (- w38 );
  /* #120: @39 = @5[5] */
  for (rr=(&w39), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #121: @40 = @5[4] */
  for (rr=(&w40), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #122: @41 = horzcat(@37, @38, @39, @40) */
  rr=w41;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #123: @41 = @41' */
  /* #124: @21 = horzcat(@14, @15, @16, @41) */
  rr=w21;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<4; ++i) *rr++ = *cs++;
  /* #125: @18 = @21' */
  for (i=0, rr=w18, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #126: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #127: @37 = @5[0] */
  for (rr=(&w37), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #128: @38 = @5[1] */
  for (rr=(&w38), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #129: @38 = (-@38) */
  w38 = (- w38 );
  /* #130: @39 = @5[2] */
  for (rr=(&w39), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #131: @39 = (-@39) */
  w39 = (- w39 );
  /* #132: @40 = @5[3] */
  for (rr=(&w40), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #133: @40 = (-@40) */
  w40 = (- w40 );
  /* #134: @14 = vertcat(@37, @38, @39, @40) */
  rr=w14;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  /* #135: @11 = mac(@18,@14,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w18+j, ct=w14+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #136: @37 = @11[1] */
  for (rr=(&w37), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #137: @37 = (@36*@37) */
  w37  = (w36*w37);
  /* #138: @38 = 0.5 */
  w38 = 5.0000000000000000e-01;
  /* #139: @39 = @11[2] */
  for (rr=(&w39), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #140: @39 = (@38*@39) */
  w39  = (w38*w39);
  /* #141: @40 = 0.5 */
  w40 = 5.0000000000000000e-01;
  /* #142: @42 = @11[3] */
  for (rr=(&w42), cs=w11+3; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #143: @42 = (@40*@42) */
  w42  = (w40*w42);
  /* #144: @5 = vertcat(@2, @9, @28, @31, @32, @37, @39, @42) */
  rr=w05;
  *rr++ = w02;
  *rr++ = w09;
  *rr++ = w28;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w37;
  *rr++ = w39;
  *rr++ = w42;
  /* #145: @34 = @5' */
  casadi_copy(w05, 8, w34);
  /* #146: @24 = zeros(8x8) */
  casadi_clear(w24, 64);
  /* #147: @20 = input[3][1] */
  wr20 = arg[3] ? arg[3]+18 : casadi_zeros;
  /* #148: @2 = @20[7] */
  w02 = wr20[7];
  /* #149: (@24[0] = @2) */
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #150: @2 = @20[8] */
  w02 = wr20[8];
  /* #151: (@24[9] = @2) */
  for (rr=w24+9, cs=(&w02); rr!=w24+10; rr+=1) *rr = *cs++;
  /* #152: @2 = @20[9] */
  w02 = wr20[9];
  /* #153: (@24[18] = @2) */
  for (rr=w24+18, cs=(&w02); rr!=w24+19; rr+=1) *rr = *cs++;
  /* #154: @2 = @20[10] */
  w02 = wr20[10];
  /* #155: (@24[27] = @2) */
  for (rr=w24+27, cs=(&w02); rr!=w24+28; rr+=1) *rr = *cs++;
  /* #156: @2 = @20[0] */
  w02 = wr20[0];
  /* #157: (@24[36] = @2) */
  for (rr=w24+36, cs=(&w02); rr!=w24+37; rr+=1) *rr = *cs++;
  /* #158: @2 = @20[1] */
  w02 = wr20[1];
  /* #159: (@24[45] = @2) */
  for (rr=w24+45, cs=(&w02); rr!=w24+46; rr+=1) *rr = *cs++;
  /* #160: @2 = @20[2] */
  w02 = wr20[2];
  /* #161: (@24[54] = @2) */
  for (rr=w24+54, cs=(&w02); rr!=w24+55; rr+=1) *rr = *cs++;
  /* #162: @2 = @20[3] */
  w02 = wr20[3];
  /* #163: (@24[63] = @2) */
  for (rr=w24+63, cs=(&w02); rr!=w24+64; rr+=1) *rr = *cs++;
  /* #164: @1 = mac(@34,@24,@1) */
  for (i=0, rr=w01; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w34+j, ct=w24+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #165: @0 = mac(@1,@5,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w05+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #166: @2 = 0 */
  w02 = 0.;
  /* #167: @11 = zeros(1x4) */
  casadi_clear(w11, 4);
  /* #168: @15 = @6[14:18] */
  wr15 = wr06+14;
  /* #169: @32 = input[1][0] */
  w32 = arg[1] ? arg[1][0] : 0;
  /* #170: @37 = input[1][1] */
  w37 = arg[1] ? arg[1][1] : 0;
  /* #171: @39 = input[1][2] */
  w39 = arg[1] ? arg[1][2] : 0;
  /* #172: @42 = input[1][3] */
  w42 = arg[1] ? arg[1][3] : 0;
  /* #173: @16 = vertcat(@32, @37, @39, @42) */
  rr=w16;
  *rr++ = w32;
  *rr++ = w37;
  *rr++ = w39;
  *rr++ = w42;
  /* #174: @15 = (@15-@16) */
  for (i=0, rr=w15, cr=wr15, cs=w16; i<4; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #175: @16 = @15' */
  casadi_copy(w15, 4, w16);
  /* #176: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #177: @41 = @20[28:32] */
  wr41 = wr20+28;
  /* #178: @32 = @20[28] */
  w32 = wr20[28];
  /* #179: @37 = 52 */
  w37 = 52.;
  /* #180: @32 = (@32/@37) */
  w32 /= w37;
  /* #181: (@41[0] = @32) */
  casadi_copy(wr41, 4, w41);
  for (rr=w41+0, cs=(&w32); rr!=w41+1; rr+=1) *rr = *cs++;
  /* #182: @32 = @41[1] */
  for (rr=(&w32), cs=w41+1; cs!=w41+2; cs+=1) *rr++ = *cs;
  /* #183: @37 = 0.35 */
  w37 = 3.4999999999999998e-01;
  /* #184: @32 = (@32/@37) */
  w32 /= w37;
  /* #185: (@41[1] = @32) */
  for (rr=w41+1, cs=(&w32); rr!=w41+2; rr+=1) *rr = *cs++;
  /* #186: @32 = @41[2] */
  for (rr=(&w32), cs=w41+2; cs!=w41+3; cs+=1) *rr++ = *cs;
  /* #187: @37 = 0.35 */
  w37 = 3.4999999999999998e-01;
  /* #188: @32 = (@32/@37) */
  w32 /= w37;
  /* #189: (@41[2] = @32) */
  for (rr=w41+2, cs=(&w32); rr!=w41+3; rr+=1) *rr = *cs++;
  /* #190: @32 = @41[3] */
  for (rr=(&w32), cs=w41+3; cs!=w41+4; cs+=1) *rr++ = *cs;
  /* #191: @37 = 0.35 */
  w37 = 3.4999999999999998e-01;
  /* #192: @32 = (@32/@37) */
  w32 /= w37;
  /* #193: (@41[3] = @32) */
  for (rr=w41+3, cs=(&w32); rr!=w41+4; rr+=1) *rr = *cs++;
  /* #194: @32 = @41[0] */
  for (rr=(&w32), cs=w41+0; cs!=w41+1; cs+=1) *rr++ = *cs;
  /* #195: (@21[0] = @32) */
  for (rr=w21+0, cs=(&w32); rr!=w21+1; rr+=1) *rr = *cs++;
  /* #196: @32 = @41[1] */
  for (rr=(&w32), cs=w41+1; cs!=w41+2; cs+=1) *rr++ = *cs;
  /* #197: (@21[5] = @32) */
  for (rr=w21+5, cs=(&w32); rr!=w21+6; rr+=1) *rr = *cs++;
  /* #198: @32 = @41[2] */
  for (rr=(&w32), cs=w41+2; cs!=w41+3; cs+=1) *rr++ = *cs;
  /* #199: (@21[10] = @32) */
  for (rr=w21+10, cs=(&w32); rr!=w21+11; rr+=1) *rr = *cs++;
  /* #200: @32 = @41[3] */
  for (rr=(&w32), cs=w41+3; cs!=w41+4; cs+=1) *rr++ = *cs;
  /* #201: (@21[15] = @32) */
  for (rr=w21+15, cs=(&w32); rr!=w21+16; rr+=1) *rr = *cs++;
  /* #202: @11 = mac(@16,@21,@11) */
  for (i=0, rr=w11; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w16+j, ct=w21+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #203: @2 = mac(@11,@15,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w15+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #204: @0 = (@0+@2) */
  w00 += w02;
  /* #205: @2 = 0 */
  w02 = 0.;
  /* #206: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #207: @43 = @33[11:14] */
  for (rr=w43, cs=w33+11; cs!=w33+14; cs+=1) *rr++ = *cs;
  /* #208: @44 = @6[11:14] */
  wr44 = wr06+11;
  /* #209: @43 = (@43-@44) */
  for (i=0, rr=w43, cs=wr44; i<3; ++i) (*rr++) -= (*cs++);
  /* #210: @44 = @43' */
  casadi_copy(w43, 3, w44);
  /* #211: @45 = zeros(3x3) */
  casadi_clear(w45, 9);
  /* #212: @32 = @20[4] */
  w32 = wr20[4];
  /* #213: (@45[0] = @32) */
  for (rr=w45+0, cs=(&w32); rr!=w45+1; rr+=1) *rr = *cs++;
  /* #214: @32 = @20[5] */
  w32 = wr20[5];
  /* #215: (@45[4] = @32) */
  for (rr=w45+4, cs=(&w32); rr!=w45+5; rr+=1) *rr = *cs++;
  /* #216: @32 = @20[6] */
  w32 = wr20[6];
  /* #217: (@45[8] = @32) */
  for (rr=w45+8, cs=(&w32); rr!=w45+9; rr+=1) *rr = *cs++;
  /* #218: @35 = mac(@44,@45,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w44+j, ct=w45+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #219: @2 = mac(@35,@43,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w43+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #220: @0 = (@0+@2) */
  w00 += w02;
  /* #221: @2 = 0 */
  w02 = 0.;
  /* #222: @44 = zeros(1x3) */
  casadi_clear(w44, 3);
  /* #223: @46 = @33[8:11] */
  for (rr=w46, cs=w33+8; cs!=w33+11; cs+=1) *rr++ = *cs;
  /* #224: @47 = @6[8:11] */
  wr47 = wr06+8;
  /* #225: @46 = (@46-@47) */
  for (i=0, rr=w46, cs=wr47; i<3; ++i) (*rr++) -= (*cs++);
  /* #226: @47 = @46' */
  casadi_copy(w46, 3, w47);
  /* #227: @48 = zeros(3x3) */
  casadi_clear(w48, 9);
  /* #228: @32 = @20[11] */
  w32 = wr20[11];
  /* #229: (@48[0] = @32) */
  for (rr=w48+0, cs=(&w32); rr!=w48+1; rr+=1) *rr = *cs++;
  /* #230: @32 = @20[12] */
  w32 = wr20[12];
  /* #231: (@48[4] = @32) */
  for (rr=w48+4, cs=(&w32); rr!=w48+5; rr+=1) *rr = *cs++;
  /* #232: @32 = @20[13] */
  w32 = wr20[13];
  /* #233: (@48[8] = @32) */
  for (rr=w48+8, cs=(&w32); rr!=w48+9; rr+=1) *rr = *cs++;
  /* #234: @44 = mac(@47,@48,@44) */
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w48+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #235: @2 = mac(@44,@46,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w44+j, ct=w46+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #236: @0 = (@0+@2) */
  w00 += w02;
  /* #237: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #238: @11 = @11' */
  /* #239: @16 = zeros(1x4) */
  casadi_clear(w16, 4);
  /* #240: @15 = @15' */
  /* #241: @17 = @21' */
  for (i=0, rr=w17, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #242: @16 = mac(@15,@17,@16) */
  for (i=0, rr=w16; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w15+j, ct=w17+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #243: @16 = @16' */
  /* #244: @11 = (@11+@16) */
  for (i=0, rr=w11, cs=w16; i<4; ++i) (*rr++) += (*cs++);
  /* #245: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #246: {@0, @2, @32, @37} = vertsplit(@11) */
  w00 = w11[0];
  w02 = w11[1];
  w32 = w11[2];
  w37 = w11[3];
  /* #247: output[1][0] = @0 */
  if (res[1]) res[1][0] = w00;
  /* #248: output[1][1] = @2 */
  if (res[1]) res[1][1] = w02;
  /* #249: output[1][2] = @32 */
  if (res[1]) res[1][2] = w32;
  /* #250: output[1][3] = @37 */
  if (res[1]) res[1][3] = w37;
  /* #251: @33 = zeros(14x1) */
  casadi_clear(w33, 14);
  /* #252: @44 = @44' */
  /* #253: @47 = zeros(1x3) */
  casadi_clear(w47, 3);
  /* #254: @46 = @46' */
  /* #255: @49 = @48' */
  for (i=0, rr=w49, cs=w48; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #256: @47 = mac(@46,@49,@47) */
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w46+j, ct=w49+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #257: @47 = @47' */
  /* #258: @44 = (@44+@47) */
  for (i=0, rr=w44, cs=w47; i<3; ++i) (*rr++) += (*cs++);
  /* #259: (@33[8:11] += @44) */
  for (rr=w33+8, cs=w44; rr!=w33+11; rr+=1) *rr += *cs++;
  /* #260: @35 = @35' */
  /* #261: @44 = zeros(1x3) */
  casadi_clear(w44, 3);
  /* #262: @43 = @43' */
  /* #263: @49 = @45' */
  for (i=0, rr=w49, cs=w45; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #264: @44 = mac(@43,@49,@44) */
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w43+j, ct=w49+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #265: @44 = @44' */
  /* #266: @35 = (@35+@44) */
  for (i=0, rr=w35, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #267: (@33[11:14] += @35) */
  for (rr=w33+11, cs=w35; rr!=w33+14; rr+=1) *rr += *cs++;
  /* #268: @34 = zeros(8x1) */
  casadi_clear(w34, 8);
  /* #269: @50 = zeros(8x1) */
  casadi_clear(w50, 8);
  /* #270: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #271: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #272: @16 = zeros(4x1) */
  casadi_clear(w16, 4);
  /* #273: @1 = @1' */
  /* #274: @51 = zeros(1x8) */
  casadi_clear(w51, 8);
  /* #275: @5 = @5' */
  /* #276: @52 = @24' */
  for (i=0, rr=w52, cs=w24; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #277: @51 = mac(@5,@52,@51) */
  for (i=0, rr=w51; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w05+j, ct=w52+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #278: @51 = @51' */
  /* #279: @1 = (@1+@51) */
  for (i=0, rr=w01, cs=w51; i<8; ++i) (*rr++) += (*cs++);
  /* #280: {NULL, @37, @32, @2, NULL, @0, @39, @42} = vertsplit(@1) */
  w37 = w01[1];
  w32 = w01[2];
  w02 = w01[3];
  w00 = w01[5];
  w39 = w01[6];
  w42 = w01[7];
  /* #281: @40 = (@40*@42) */
  w40 *= w42;
  /* #282: (@16[3] += @40) */
  for (rr=w16+3, cs=(&w40); rr!=w16+4; rr+=1) *rr += *cs++;
  /* #283: @38 = (@38*@39) */
  w38 *= w39;
  /* #284: (@16[2] += @38) */
  for (rr=w16+2, cs=(&w38); rr!=w16+3; rr+=1) *rr += *cs++;
  /* #285: @36 = (@36*@0) */
  w36 *= w00;
  /* #286: (@16[1] += @36) */
  for (rr=w16+1, cs=(&w36); rr!=w16+2; rr+=1) *rr += *cs++;
  /* #287: @11 = mac(@17,@16,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w17+j, ct=w16+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #288: {@36, @0, @38, @39} = vertsplit(@11) */
  w36 = w11[0];
  w00 = w11[1];
  w38 = w11[2];
  w39 = w11[3];
  /* #289: @39 = (-@39) */
  w39 = (- w39 );
  /* #290: (@50[3] += @39) */
  for (rr=w50+3, cs=(&w39); rr!=w50+4; rr+=1) *rr += *cs++;
  /* #291: @38 = (-@38) */
  w38 = (- w38 );
  /* #292: (@50[2] += @38) */
  for (rr=w50+2, cs=(&w38); rr!=w50+3; rr+=1) *rr += *cs++;
  /* #293: @0 = (-@0) */
  w00 = (- w00 );
  /* #294: (@50[1] += @0) */
  for (rr=w50+1, cs=(&w00); rr!=w50+2; rr+=1) *rr += *cs++;
  /* #295: (@50[0] += @36) */
  for (rr=w50+0, cs=(&w36); rr!=w50+1; rr+=1) *rr += *cs++;
  /* #296: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #297: @14 = @14' */
  /* #298: @17 = mac(@16,@14,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w16+j, ct=w14+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #299: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #300: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #301: {@16, @14, @11, @15} = horzsplit(@18) */
  casadi_copy(w18, 4, w16);
  casadi_copy(w18+4, 4, w14);
  casadi_copy(w18+8, 4, w11);
  casadi_copy(w18+12, 4, w15);
  /* #302: @15 = @15' */
  /* #303: {@36, @0, @38, @39} = horzsplit(@15) */
  w36 = w15[0];
  w00 = w15[1];
  w38 = w15[2];
  w39 = w15[3];
  /* #304: (@50[4] += @39) */
  for (rr=w50+4, cs=(&w39); rr!=w50+5; rr+=1) *rr += *cs++;
  /* #305: (@50[5] += @38) */
  for (rr=w50+5, cs=(&w38); rr!=w50+6; rr+=1) *rr += *cs++;
  /* #306: @0 = (-@0) */
  w00 = (- w00 );
  /* #307: (@50[6] += @0) */
  for (rr=w50+6, cs=(&w00); rr!=w50+7; rr+=1) *rr += *cs++;
  /* #308: (@50[7] += @36) */
  for (rr=w50+7, cs=(&w36); rr!=w50+8; rr+=1) *rr += *cs++;
  /* #309: @11 = @11' */
  /* #310: {@36, @0, @38, @39} = horzsplit(@11) */
  w36 = w11[0];
  w00 = w11[1];
  w38 = w11[2];
  w39 = w11[3];
  /* #311: @39 = (-@39) */
  w39 = (- w39 );
  /* #312: (@50[5] += @39) */
  for (rr=w50+5, cs=(&w39); rr!=w50+6; rr+=1) *rr += *cs++;
  /* #313: (@50[4] += @38) */
  for (rr=w50+4, cs=(&w38); rr!=w50+5; rr+=1) *rr += *cs++;
  /* #314: (@50[7] += @0) */
  for (rr=w50+7, cs=(&w00); rr!=w50+8; rr+=1) *rr += *cs++;
  /* #315: (@50[6] += @36) */
  for (rr=w50+6, cs=(&w36); rr!=w50+7; rr+=1) *rr += *cs++;
  /* #316: @14 = @14' */
  /* #317: {@36, @0, @38, @39} = horzsplit(@14) */
  w36 = w14[0];
  w00 = w14[1];
  w38 = w14[2];
  w39 = w14[3];
  /* #318: (@50[6] += @39) */
  for (rr=w50+6, cs=(&w39); rr!=w50+7; rr+=1) *rr += *cs++;
  /* #319: @38 = (-@38) */
  w38 = (- w38 );
  /* #320: (@50[7] += @38) */
  for (rr=w50+7, cs=(&w38); rr!=w50+8; rr+=1) *rr += *cs++;
  /* #321: (@50[4] += @0) */
  for (rr=w50+4, cs=(&w00); rr!=w50+5; rr+=1) *rr += *cs++;
  /* #322: (@50[5] += @36) */
  for (rr=w50+5, cs=(&w36); rr!=w50+6; rr+=1) *rr += *cs++;
  /* #323: @16 = @16' */
  /* #324: {@36, @0, @38, @39} = horzsplit(@16) */
  w36 = w16[0];
  w00 = w16[1];
  w38 = w16[2];
  w39 = w16[3];
  /* #325: @39 = (-@39) */
  w39 = (- w39 );
  /* #326: (@50[7] += @39) */
  for (rr=w50+7, cs=(&w39); rr!=w50+8; rr+=1) *rr += *cs++;
  /* #327: @38 = (-@38) */
  w38 = (- w38 );
  /* #328: (@50[6] += @38) */
  for (rr=w50+6, cs=(&w38); rr!=w50+7; rr+=1) *rr += *cs++;
  /* #329: @0 = (-@0) */
  w00 = (- w00 );
  /* #330: (@50[5] += @0) */
  for (rr=w50+5, cs=(&w00); rr!=w50+6; rr+=1) *rr += *cs++;
  /* #331: (@50[4] += @36) */
  for (rr=w50+4, cs=(&w36); rr!=w50+5; rr+=1) *rr += *cs++;
  /* #332: @36 = (@2/@13) */
  w36  = (w02/w13);
  /* #333: @10 = (@10*@36) */
  w10 *= w36;
  /* #334: (@50[3] += @10) */
  for (rr=w50+3, cs=(&w10); rr!=w50+4; rr+=1) *rr += *cs++;
  /* #335: @10 = (@32/@13) */
  w10  = (w32/w13);
  /* #336: @26 = (@26*@10) */
  w26 *= w10;
  /* #337: (@50[2] += @26) */
  for (rr=w50+2, cs=(&w26); rr!=w50+3; rr+=1) *rr += *cs++;
  /* #338: @26 = (@37/@13) */
  w26  = (w37/w13);
  /* #339: @8 = (@8*@26) */
  w08 *= w26;
  /* #340: (@50[1] += @8) */
  for (rr=w50+1, cs=(&w08); rr!=w50+2; rr+=1) *rr += *cs++;
  /* #341: @8 = sq(@13) */
  w08 = casadi_sq( w13 );
  /* #342: @0 = sq(@7) */
  w00 = casadi_sq( w07 );
  /* #343: @8 = (@8+@0) */
  w08 += w00;
  /* #344: @0 = (@13/@8) */
  w00  = (w13/w08);
  /* #345: @30 = (@30*@36) */
  w30 *= w36;
  /* #346: @29 = (@29*@30) */
  w29 *= w30;
  /* #347: @27 = (@27*@10) */
  w27 *= w10;
  /* #348: @25 = (@25*@27) */
  w25 *= w27;
  /* #349: @29 = (@29+@25) */
  w29 += w25;
  /* #350: @12 = (@12*@26) */
  w12 *= w26;
  /* #351: @3 = (@3*@12) */
  w03 *= w12;
  /* #352: @29 = (@29+@3) */
  w29 += w03;
  /* #353: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #354: @0 = (@0*@29) */
  w00 *= w29;
  /* #355: @0 = (-@0) */
  w00 = (- w00 );
  /* #356: (@50[0] += @0) */
  for (rr=w50+0, cs=(&w00); rr!=w50+1; rr+=1) *rr += *cs++;
  /* #357: @28 = (@28/@13) */
  w28 /= w13;
  /* #358: @28 = (@28*@32) */
  w28 *= w32;
  /* #359: @28 = (-@28) */
  w28 = (- w28 );
  /* #360: @31 = (@31/@13) */
  w31 /= w13;
  /* #361: @31 = (@31*@2) */
  w31 *= w02;
  /* #362: @28 = (@28-@31) */
  w28 -= w31;
  /* #363: @9 = (@9/@13) */
  w09 /= w13;
  /* #364: @9 = (@9*@37) */
  w09 *= w37;
  /* #365: @28 = (@28-@9) */
  w28 -= w09;
  /* #366: @7 = (@7/@8) */
  w07 /= w08;
  /* #367: @7 = (@7*@29) */
  w07 *= w29;
  /* #368: @28 = (@28+@7) */
  w28 += w07;
  /* #369: @28 = (@28/@13) */
  w28 /= w13;
  /* #370: @4 = (@28*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w28*(*cs++));
  /* #371: (@50[1:4] += @4) */
  for (rr=w50+1, cs=w04; rr!=w50+4; rr+=1) *rr += *cs++;
  /* #372: @34 = mac(@23,@50,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w23+j, ct=w50+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #373: (@33[:8] += @34) */
  for (rr=w33+0, cs=w34; rr!=w33+8; rr+=1) *rr += *cs++;
  /* #374: {@28, @13, @7, @29, @8, @9, @37, @31, @2, @32, @0, @3, @12, @26} = vertsplit(@33) */
  w28 = w33[0];
  w13 = w33[1];
  w07 = w33[2];
  w29 = w33[3];
  w08 = w33[4];
  w09 = w33[5];
  w37 = w33[6];
  w31 = w33[7];
  w02 = w33[8];
  w32 = w33[9];
  w00 = w33[10];
  w03 = w33[11];
  w12 = w33[12];
  w26 = w33[13];
  /* #375: output[1][4] = @28 */
  if (res[1]) res[1][4] = w28;
  /* #376: output[1][5] = @13 */
  if (res[1]) res[1][5] = w13;
  /* #377: output[1][6] = @7 */
  if (res[1]) res[1][6] = w07;
  /* #378: output[1][7] = @29 */
  if (res[1]) res[1][7] = w29;
  /* #379: output[1][8] = @8 */
  if (res[1]) res[1][8] = w08;
  /* #380: output[1][9] = @9 */
  if (res[1]) res[1][9] = w09;
  /* #381: output[1][10] = @37 */
  if (res[1]) res[1][10] = w37;
  /* #382: output[1][11] = @31 */
  if (res[1]) res[1][11] = w31;
  /* #383: output[1][12] = @2 */
  if (res[1]) res[1][12] = w02;
  /* #384: output[1][13] = @32 */
  if (res[1]) res[1][13] = w32;
  /* #385: output[1][14] = @0 */
  if (res[1]) res[1][14] = w00;
  /* #386: output[1][15] = @3 */
  if (res[1]) res[1][15] = w03;
  /* #387: output[1][16] = @12 */
  if (res[1]) res[1][16] = w12;
  /* #388: output[1][17] = @26 */
  if (res[1]) res[1][17] = w26;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 504;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 16*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 504*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
