/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[22] = 
  {19, 1, 0, 18, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s1[3] = {15, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {53, 1, 1};
static const casadi_int casadi_s5[3] = {1, 1, 1};
static const casadi_int casadi_s6[3] = {19, 1, 1};

static const casadi_real casadi_zeros[34] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* quadrotor_cost_ext_cost_0_fun_jac:(i0[15],i1[4],i2[],i3[53])->(o0,o1[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+9, w02, w03, *w04=w+19, *w05=w+22, *w06=w+30, w07, w08, w09, w10;
  casadi_real *w11=w+53, w12, w13, *w14=w+59, *w15=w+63, *w16=w+67, *w17=w+71, *w18=w+87, *w19=w+103, *w20=w+135, *w21=w+167, *w22=w+183;
  casadi_real *w23=w+215, *w24=w+279, w25, w26, w27, w28, w29, w30, w31, w32, w33, *w34=w+352;
  casadi_real *w35=w+367, *w36=w+375, w37, w38, w39, w40, w41, *w42=w+383, w43, *w45=w+422, *w46=w+425, *w47=w+428;
  casadi_real *w48=w+437, *w49=w+440, *w50=w+443, *w52=w+452, *w53=w+461, *w54=w+469, *w55=w+477, w56, w57, w58, *w59=w+544;
  const casadi_real *cr, *cs, *ct, *wr06, *wr15, *wr42, *wr44, *wr46, *wr49;
  /* #0: @0 = 0 */
  w00 = 0.;
  /* #1: @1 = zeros(1x8) */
  casadi_clear(w01, 8);
  /* #2: @2 = 0 */
  w02 = 0.;
  /* #3: @3 = 0.5 */
  w03 = 5.0000000000000000e-01;
  /* #4: @4 = all_2.22045e-16(3x1) */
  casadi_fill(w04, 3, 2.2204460492503131e-16);
  /* #5: @5 = zeros(8x1) */
  casadi_clear(w05, 8);
  /* #6: @6 = input[3][0] */
  wr06 = arg[3] ? arg[3] : casadi_zeros;
  /* #7: @7 = @6[0] */
  w07 = wr06[0];
  /* #8: @8 = @6[1] */
  w08 = wr06[1];
  /* #9: @9 = @6[2] */
  w09 = wr06[2];
  /* #10: @10 = @6[3] */
  w10 = wr06[3];
  /* #11: @11 = horzcat(@7, @8, @9, @10) */
  rr=w11;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  /* #12: @11 = @11' */
  /* #13: @7 = (-@8) */
  w07 = (- w08 );
  /* #14: @12 = @6[0] */
  w12 = wr06[0];
  /* #15: @13 = (-@9) */
  w13 = (- w09 );
  /* #16: @14 = horzcat(@7, @12, @10, @13) */
  rr=w14;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w10;
  *rr++ = w13;
  /* #17: @14 = @14' */
  /* #18: @10 = (-@10) */
  w10 = (- w10 );
  /* #19: @12 = @6[0] */
  w12 = wr06[0];
  /* #20: @15 = horzcat(@13, @10, @12, @8) */
  rr=w15;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w08;
  /* #21: @15 = @15' */
  /* #22: @13 = @6[0] */
  w13 = wr06[0];
  /* #23: @16 = horzcat(@10, @9, @7, @13) */
  rr=w16;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w13;
  /* #24: @16 = @16' */
  /* #25: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #26: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #27: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #28: @19 = horzcat(@18, @17) */
  rr=w19;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #29: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #30: @10 = @6[4] */
  w10 = wr06[4];
  /* #31: @9 = @6[5] */
  w09 = wr06[5];
  /* #32: @7 = @6[6] */
  w07 = wr06[6];
  /* #33: @13 = @6[7] */
  w13 = wr06[7];
  /* #34: @11 = horzcat(@10, @9, @7, @13) */
  rr=w11;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w07;
  *rr++ = w13;
  /* #35: @11 = @11' */
  /* #36: @10 = (-@9) */
  w10 = (- w09 );
  /* #37: @12 = @6[4] */
  w12 = wr06[4];
  /* #38: @8 = (-@7) */
  w08 = (- w07 );
  /* #39: @14 = horzcat(@10, @12, @13, @8) */
  rr=w14;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w08;
  /* #40: @14 = @14' */
  /* #41: @13 = (-@13) */
  w13 = (- w13 );
  /* #42: @12 = @6[4] */
  w12 = wr06[4];
  /* #43: @15 = horzcat(@8, @13, @12, @9) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w09;
  /* #44: @15 = @15' */
  /* #45: @8 = @6[4] */
  w08 = wr06[4];
  /* #46: @16 = horzcat(@13, @7, @10, @8) */
  rr=w16;
  *rr++ = w13;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w08;
  /* #47: @16 = @16' */
  /* #48: @17 = horzcat(@11, @14, @15, @16) */
  rr=w17;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  /* #49: @21 = @17' */
  for (i=0, rr=w21, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #50: @19 = horzcat(@21, @18) */
  rr=w19;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #51: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #52: @23 = horzcat(@20, @22) */
  rr=w23;
  for (i=0, cs=w20; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<32; ++i) *rr++ = *cs++;
  /* #53: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #54: @13 = input[0][0] */
  w13 = arg[0] ? arg[0][0] : 0;
  /* #55: @7 = input[0][1] */
  w07 = arg[0] ? arg[0][1] : 0;
  /* #56: @10 = input[0][2] */
  w10 = arg[0] ? arg[0][2] : 0;
  /* #57: @8 = input[0][3] */
  w08 = arg[0] ? arg[0][3] : 0;
  /* #58: @12 = input[0][4] */
  w12 = arg[0] ? arg[0][4] : 0;
  /* #59: @9 = input[0][5] */
  w09 = arg[0] ? arg[0][5] : 0;
  /* #60: @25 = input[0][6] */
  w25 = arg[0] ? arg[0][6] : 0;
  /* #61: @26 = input[0][7] */
  w26 = arg[0] ? arg[0][7] : 0;
  /* #62: @27 = input[0][8] */
  w27 = arg[0] ? arg[0][8] : 0;
  /* #63: @28 = input[0][9] */
  w28 = arg[0] ? arg[0][9] : 0;
  /* #64: @29 = input[0][10] */
  w29 = arg[0] ? arg[0][10] : 0;
  /* #65: @30 = input[0][11] */
  w30 = arg[0] ? arg[0][11] : 0;
  /* #66: @31 = input[0][12] */
  w31 = arg[0] ? arg[0][12] : 0;
  /* #67: @32 = input[0][13] */
  w32 = arg[0] ? arg[0][13] : 0;
  /* #68: @33 = input[0][14] */
  w33 = arg[0] ? arg[0][14] : 0;
  /* #69: @34 = vertcat(@13, @7, @10, @8, @12, @9, @25, @26, @27, @28, @29, @30, @31, @32, @33) */
  rr=w34;
  *rr++ = w13;
  *rr++ = w07;
  *rr++ = w10;
  *rr++ = w08;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w33;
  /* #70: @35 = @34[:8] */
  for (rr=w35, cs=w34+0; cs!=w34+8; cs+=1) *rr++ = *cs;
  /* #71: @5 = mac(@24,@35,@5) */
  for (i=0, rr=w05; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w24+j, ct=w35+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #72: @36 = @5[1:4] */
  for (rr=w36, cs=w05+1; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #73: @4 = (@4+@36) */
  for (i=0, rr=w04, cs=w36; i<3; ++i) (*rr++) += (*cs++);
  /* #74: @13 = ||@4||_F */
  w13 = casadi_norm_2(3, w04);
  /* #75: @7 = @5[0] */
  for (rr=(&w07), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #76: @10 = atan2(@13,@7) */
  w10  = atan2(w13,w07);
  /* #77: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #78: @8 = (@3*@10) */
  w08  = (w03*w10);
  /* #79: @12 = @5[1] */
  for (rr=(&w12), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #80: @9 = (@8*@12) */
  w09  = (w08*w12);
  /* #81: @9 = (@9/@13) */
  w09 /= w13;
  /* #82: @25 = 0.5 */
  w25 = 5.0000000000000000e-01;
  /* #83: @26 = (@25*@10) */
  w26  = (w25*w10);
  /* #84: @27 = @5[2] */
  for (rr=(&w27), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #85: @28 = (@26*@27) */
  w28  = (w26*w27);
  /* #86: @28 = (@28/@13) */
  w28 /= w13;
  /* #87: @29 = 0.5 */
  w29 = 5.0000000000000000e-01;
  /* #88: @10 = (@29*@10) */
  w10  = (w29*w10);
  /* #89: @30 = @5[3] */
  for (rr=(&w30), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #90: @31 = (@10*@30) */
  w31  = (w10*w30);
  /* #91: @31 = (@31/@13) */
  w31 /= w13;
  /* #92: @32 = 0 */
  w32 = 0.;
  /* #93: @37 = 0.5 */
  w37 = 5.0000000000000000e-01;
  /* #94: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #95: @38 = @5[4] */
  for (rr=(&w38), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #96: @39 = @5[5] */
  for (rr=(&w39), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #97: @39 = (-@39) */
  w39 = (- w39 );
  /* #98: @40 = @5[6] */
  for (rr=(&w40), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #99: @40 = (-@40) */
  w40 = (- w40 );
  /* #100: @41 = @5[7] */
  for (rr=(&w41), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #101: @41 = (-@41) */
  w41 = (- w41 );
  /* #102: @14 = horzcat(@38, @39, @40, @41) */
  rr=w14;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #103: @14 = @14' */
  /* #104: @38 = @5[5] */
  for (rr=(&w38), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #105: @39 = @5[4] */
  for (rr=(&w39), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #106: @40 = @5[7] */
  for (rr=(&w40), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #107: @40 = (-@40) */
  w40 = (- w40 );
  /* #108: @41 = @5[6] */
  for (rr=(&w41), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #109: @15 = horzcat(@38, @39, @40, @41) */
  rr=w15;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #110: @15 = @15' */
  /* #111: @38 = @5[6] */
  for (rr=(&w38), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #112: @39 = @5[7] */
  for (rr=(&w39), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #113: @40 = @5[4] */
  for (rr=(&w40), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #114: @41 = @5[5] */
  for (rr=(&w41), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #115: @41 = (-@41) */
  w41 = (- w41 );
  /* #116: @16 = horzcat(@38, @39, @40, @41) */
  rr=w16;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #117: @16 = @16' */
  /* #118: @38 = @5[7] */
  for (rr=(&w38), cs=w05+7; cs!=w05+8; cs+=1) *rr++ = *cs;
  /* #119: @39 = @5[6] */
  for (rr=(&w39), cs=w05+6; cs!=w05+7; cs+=1) *rr++ = *cs;
  /* #120: @39 = (-@39) */
  w39 = (- w39 );
  /* #121: @40 = @5[5] */
  for (rr=(&w40), cs=w05+5; cs!=w05+6; cs+=1) *rr++ = *cs;
  /* #122: @41 = @5[4] */
  for (rr=(&w41), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #123: @42 = horzcat(@38, @39, @40, @41) */
  rr=w42;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #124: @42 = @42' */
  /* #125: @21 = horzcat(@14, @15, @16, @42) */
  rr=w21;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<4; ++i) *rr++ = *cs++;
  /* #126: @18 = @21' */
  for (i=0, rr=w18, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #127: @18 = (2.*@18) */
  for (i=0, rr=w18, cs=w18; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #128: @38 = @5[0] */
  for (rr=(&w38), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #129: @39 = @5[1] */
  for (rr=(&w39), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #130: @39 = (-@39) */
  w39 = (- w39 );
  /* #131: @40 = @5[2] */
  for (rr=(&w40), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #132: @40 = (-@40) */
  w40 = (- w40 );
  /* #133: @41 = @5[3] */
  for (rr=(&w41), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #134: @41 = (-@41) */
  w41 = (- w41 );
  /* #135: @14 = vertcat(@38, @39, @40, @41) */
  rr=w14;
  *rr++ = w38;
  *rr++ = w39;
  *rr++ = w40;
  *rr++ = w41;
  /* #136: @11 = mac(@18,@14,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w18+j, ct=w14+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #137: @38 = @11[1] */
  for (rr=(&w38), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #138: @38 = (@37*@38) */
  w38  = (w37*w38);
  /* #139: @39 = 0.5 */
  w39 = 5.0000000000000000e-01;
  /* #140: @40 = @11[2] */
  for (rr=(&w40), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #141: @40 = (@39*@40) */
  w40  = (w39*w40);
  /* #142: @41 = 0.5 */
  w41 = 5.0000000000000000e-01;
  /* #143: @43 = @11[3] */
  for (rr=(&w43), cs=w11+3; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #144: @43 = (@41*@43) */
  w43  = (w41*w43);
  /* #145: @5 = vertcat(@2, @9, @28, @31, @32, @38, @40, @43) */
  rr=w05;
  *rr++ = w02;
  *rr++ = w09;
  *rr++ = w28;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w38;
  *rr++ = w40;
  *rr++ = w43;
  /* #146: @35 = @5' */
  casadi_copy(w05, 8, w35);
  /* #147: @24 = zeros(8x8) */
  casadi_clear(w24, 64);
  /* #148: @44 = input[3][1] */
  wr44 = arg[3] ? arg[3]+19 : casadi_zeros;
  /* #149: @2 = @44[7] */
  w02 = wr44[7];
  /* #150: (@24[0] = @2) */
  for (rr=w24+0, cs=(&w02); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #151: @2 = @44[8] */
  w02 = wr44[8];
  /* #152: (@24[9] = @2) */
  for (rr=w24+9, cs=(&w02); rr!=w24+10; rr+=1) *rr = *cs++;
  /* #153: @2 = @44[9] */
  w02 = wr44[9];
  /* #154: (@24[18] = @2) */
  for (rr=w24+18, cs=(&w02); rr!=w24+19; rr+=1) *rr = *cs++;
  /* #155: @2 = @44[10] */
  w02 = wr44[10];
  /* #156: (@24[27] = @2) */
  for (rr=w24+27, cs=(&w02); rr!=w24+28; rr+=1) *rr = *cs++;
  /* #157: @2 = @44[0] */
  w02 = wr44[0];
  /* #158: (@24[36] = @2) */
  for (rr=w24+36, cs=(&w02); rr!=w24+37; rr+=1) *rr = *cs++;
  /* #159: @2 = @44[1] */
  w02 = wr44[1];
  /* #160: (@24[45] = @2) */
  for (rr=w24+45, cs=(&w02); rr!=w24+46; rr+=1) *rr = *cs++;
  /* #161: @2 = @44[2] */
  w02 = wr44[2];
  /* #162: (@24[54] = @2) */
  for (rr=w24+54, cs=(&w02); rr!=w24+55; rr+=1) *rr = *cs++;
  /* #163: @2 = @44[3] */
  w02 = wr44[3];
  /* #164: (@24[63] = @2) */
  for (rr=w24+63, cs=(&w02); rr!=w24+64; rr+=1) *rr = *cs++;
  /* #165: @1 = mac(@35,@24,@1) */
  for (i=0, rr=w01; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w35+j, ct=w24+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #166: @0 = mac(@1,@5,@0) */
  for (i=0, rr=(&w00); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w01+j, ct=w05+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #167: @2 = 0 */
  w02 = 0.;
  /* #168: @11 = zeros(1x4) */
  casadi_clear(w11, 4);
  /* #169: @15 = @6[15:19] */
  wr15 = wr06+15;
  /* #170: @32 = input[1][1] */
  w32 = arg[1] ? arg[1][1] : 0;
  /* #171: @38 = input[1][2] */
  w38 = arg[1] ? arg[1][2] : 0;
  /* #172: @40 = input[1][3] */
  w40 = arg[1] ? arg[1][3] : 0;
  /* #173: @16 = vertcat(@33, @32, @38, @40) */
  rr=w16;
  *rr++ = w33;
  *rr++ = w32;
  *rr++ = w38;
  *rr++ = w40;
  /* #174: @15 = (@15-@16) */
  for (i=0, rr=w15, cr=wr15, cs=w16; i<4; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #175: @16 = @15' */
  casadi_copy(w15, 4, w16);
  /* #176: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #177: @42 = @44[30:34] */
  wr42 = wr44+30;
  /* #178: @33 = @44[30] */
  w33 = wr44[30];
  /* #179: @32 = 52 */
  w32 = 52.;
  /* #180: @33 = (@33/@32) */
  w33 /= w32;
  /* #181: (@42[0] = @33) */
  casadi_copy(wr42, 4, w42);
  for (rr=w42+0, cs=(&w33); rr!=w42+1; rr+=1) *rr = *cs++;
  /* #182: @33 = @42[1] */
  for (rr=(&w33), cs=w42+1; cs!=w42+2; cs+=1) *rr++ = *cs;
  /* #183: @32 = 0.35 */
  w32 = 3.4999999999999998e-01;
  /* #184: @33 = (@33/@32) */
  w33 /= w32;
  /* #185: (@42[1] = @33) */
  for (rr=w42+1, cs=(&w33); rr!=w42+2; rr+=1) *rr = *cs++;
  /* #186: @33 = @42[2] */
  for (rr=(&w33), cs=w42+2; cs!=w42+3; cs+=1) *rr++ = *cs;
  /* #187: @32 = 0.35 */
  w32 = 3.4999999999999998e-01;
  /* #188: @33 = (@33/@32) */
  w33 /= w32;
  /* #189: (@42[2] = @33) */
  for (rr=w42+2, cs=(&w33); rr!=w42+3; rr+=1) *rr = *cs++;
  /* #190: @33 = @42[3] */
  for (rr=(&w33), cs=w42+3; cs!=w42+4; cs+=1) *rr++ = *cs;
  /* #191: @32 = 0.35 */
  w32 = 3.4999999999999998e-01;
  /* #192: @33 = (@33/@32) */
  w33 /= w32;
  /* #193: (@42[3] = @33) */
  for (rr=w42+3, cs=(&w33); rr!=w42+4; rr+=1) *rr = *cs++;
  /* #194: @33 = @42[0] */
  for (rr=(&w33), cs=w42+0; cs!=w42+1; cs+=1) *rr++ = *cs;
  /* #195: (@21[0] = @33) */
  for (rr=w21+0, cs=(&w33); rr!=w21+1; rr+=1) *rr = *cs++;
  /* #196: @33 = @42[1] */
  for (rr=(&w33), cs=w42+1; cs!=w42+2; cs+=1) *rr++ = *cs;
  /* #197: (@21[5] = @33) */
  for (rr=w21+5, cs=(&w33); rr!=w21+6; rr+=1) *rr = *cs++;
  /* #198: @33 = @42[2] */
  for (rr=(&w33), cs=w42+2; cs!=w42+3; cs+=1) *rr++ = *cs;
  /* #199: (@21[10] = @33) */
  for (rr=w21+10, cs=(&w33); rr!=w21+11; rr+=1) *rr = *cs++;
  /* #200: @33 = @42[3] */
  for (rr=(&w33), cs=w42+3; cs!=w42+4; cs+=1) *rr++ = *cs;
  /* #201: (@21[15] = @33) */
  for (rr=w21+15, cs=(&w33); rr!=w21+16; rr+=1) *rr = *cs++;
  /* #202: @11 = mac(@16,@21,@11) */
  for (i=0, rr=w11; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w16+j, ct=w21+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #203: @2 = mac(@11,@15,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w11+j, ct=w15+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #204: @0 = (@0+@2) */
  w00 += w02;
  /* #205: @2 = 0 */
  w02 = 0.;
  /* #206: @36 = zeros(1x3) */
  casadi_clear(w36, 3);
  /* #207: @45 = @34[11:14] */
  for (rr=w45, cs=w34+11; cs!=w34+14; cs+=1) *rr++ = *cs;
  /* #208: @46 = @6[11:14] */
  wr46 = wr06+11;
  /* #209: @45 = (@45-@46) */
  for (i=0, rr=w45, cs=wr46; i<3; ++i) (*rr++) -= (*cs++);
  /* #210: @46 = @45' */
  casadi_copy(w45, 3, w46);
  /* #211: @47 = zeros(3x3) */
  casadi_clear(w47, 9);
  /* #212: @33 = @44[4] */
  w33 = wr44[4];
  /* #213: (@47[0] = @33) */
  for (rr=w47+0, cs=(&w33); rr!=w47+1; rr+=1) *rr = *cs++;
  /* #214: @33 = @44[5] */
  w33 = wr44[5];
  /* #215: (@47[4] = @33) */
  for (rr=w47+4, cs=(&w33); rr!=w47+5; rr+=1) *rr = *cs++;
  /* #216: @33 = @44[6] */
  w33 = wr44[6];
  /* #217: (@47[8] = @33) */
  for (rr=w47+8, cs=(&w33); rr!=w47+9; rr+=1) *rr = *cs++;
  /* #218: @36 = mac(@46,@47,@36) */
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w46+j, ct=w47+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #219: @2 = mac(@36,@45,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w36+j, ct=w45+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #220: @0 = (@0+@2) */
  w00 += w02;
  /* #221: @2 = 0 */
  w02 = 0.;
  /* #222: @46 = zeros(1x3) */
  casadi_clear(w46, 3);
  /* #223: @48 = @34[8:11] */
  for (rr=w48, cs=w34+8; cs!=w34+11; cs+=1) *rr++ = *cs;
  /* #224: @49 = @6[8:11] */
  wr49 = wr06+8;
  /* #225: @48 = (@48-@49) */
  for (i=0, rr=w48, cs=wr49; i<3; ++i) (*rr++) -= (*cs++);
  /* #226: @49 = @48' */
  casadi_copy(w48, 3, w49);
  /* #227: @50 = zeros(3x3) */
  casadi_clear(w50, 9);
  /* #228: @33 = @44[11] */
  w33 = wr44[11];
  /* #229: (@50[0] = @33) */
  for (rr=w50+0, cs=(&w33); rr!=w50+1; rr+=1) *rr = *cs++;
  /* #230: @33 = @44[12] */
  w33 = wr44[12];
  /* #231: (@50[4] = @33) */
  for (rr=w50+4, cs=(&w33); rr!=w50+5; rr+=1) *rr = *cs++;
  /* #232: @33 = @44[13] */
  w33 = wr44[13];
  /* #233: (@50[8] = @33) */
  for (rr=w50+8, cs=(&w33); rr!=w50+9; rr+=1) *rr = *cs++;
  /* #234: @46 = mac(@49,@50,@46) */
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w49+j, ct=w50+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #235: @2 = mac(@46,@48,@2) */
  for (i=0, rr=(&w02); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w46+j, ct=w48+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #236: @0 = (@0+@2) */
  w00 += w02;
  /* #237: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #238: @51 = 00 */
  /* #239: @11 = @11' */
  /* #240: @16 = zeros(1x4) */
  casadi_clear(w16, 4);
  /* #241: @15 = @15' */
  /* #242: @17 = @21' */
  for (i=0, rr=w17, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #243: @16 = mac(@15,@17,@16) */
  for (i=0, rr=w16; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w15+j, ct=w17+i*4; k<4; ++k) *rr += cs[k*1]**ct++;
  /* #244: @16 = @16' */
  /* #245: @11 = (@11+@16) */
  for (i=0, rr=w11, cs=w16; i<4; ++i) (*rr++) += (*cs++);
  /* #246: @11 = (-@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #247: {@0, @2, @33, @32} = vertsplit(@11) */
  w00 = w11[0];
  w02 = w11[1];
  w33 = w11[2];
  w32 = w11[3];
  /* #248: @34 = zeros(15x1) */
  casadi_clear(w34, 15);
  /* #249: @46 = @46' */
  /* #250: @49 = zeros(1x3) */
  casadi_clear(w49, 3);
  /* #251: @48 = @48' */
  /* #252: @52 = @50' */
  for (i=0, rr=w52, cs=w50; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #253: @49 = mac(@48,@52,@49) */
  for (i=0, rr=w49; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w48+j, ct=w52+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #254: @49 = @49' */
  /* #255: @46 = (@46+@49) */
  for (i=0, rr=w46, cs=w49; i<3; ++i) (*rr++) += (*cs++);
  /* #256: (@34[8:11] += @46) */
  for (rr=w34+8, cs=w46; rr!=w34+11; rr+=1) *rr += *cs++;
  /* #257: @36 = @36' */
  /* #258: @46 = zeros(1x3) */
  casadi_clear(w46, 3);
  /* #259: @45 = @45' */
  /* #260: @52 = @47' */
  for (i=0, rr=w52, cs=w47; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #261: @46 = mac(@45,@52,@46) */
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w45+j, ct=w52+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #262: @46 = @46' */
  /* #263: @36 = (@36+@46) */
  for (i=0, rr=w36, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #264: (@34[11:14] += @36) */
  for (rr=w34+11, cs=w36; rr!=w34+14; rr+=1) *rr += *cs++;
  /* #265: @35 = zeros(8x1) */
  casadi_clear(w35, 8);
  /* #266: @53 = zeros(8x1) */
  casadi_clear(w53, 8);
  /* #267: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #268: @17 = @18' */
  for (i=0, rr=w17, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #269: @16 = zeros(4x1) */
  casadi_clear(w16, 4);
  /* #270: @1 = @1' */
  /* #271: @54 = zeros(1x8) */
  casadi_clear(w54, 8);
  /* #272: @5 = @5' */
  /* #273: @55 = @24' */
  for (i=0, rr=w55, cs=w24; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #274: @54 = mac(@5,@55,@54) */
  for (i=0, rr=w54; i<8; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w05+j, ct=w55+i*8; k<8; ++k) *rr += cs[k*1]**ct++;
  /* #275: @54 = @54' */
  /* #276: @1 = (@1+@54) */
  for (i=0, rr=w01, cs=w54; i<8; ++i) (*rr++) += (*cs++);
  /* #277: {NULL, @38, @40, @43, NULL, @56, @57, @58} = vertsplit(@1) */
  w38 = w01[1];
  w40 = w01[2];
  w43 = w01[3];
  w56 = w01[5];
  w57 = w01[6];
  w58 = w01[7];
  /* #278: @41 = (@41*@58) */
  w41 *= w58;
  /* #279: (@16[3] += @41) */
  for (rr=w16+3, cs=(&w41); rr!=w16+4; rr+=1) *rr += *cs++;
  /* #280: @39 = (@39*@57) */
  w39 *= w57;
  /* #281: (@16[2] += @39) */
  for (rr=w16+2, cs=(&w39); rr!=w16+3; rr+=1) *rr += *cs++;
  /* #282: @37 = (@37*@56) */
  w37 *= w56;
  /* #283: (@16[1] += @37) */
  for (rr=w16+1, cs=(&w37); rr!=w16+2; rr+=1) *rr += *cs++;
  /* #284: @11 = mac(@17,@16,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w17+j, ct=w16+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #285: {@37, @56, @39, @57} = vertsplit(@11) */
  w37 = w11[0];
  w56 = w11[1];
  w39 = w11[2];
  w57 = w11[3];
  /* #286: @57 = (-@57) */
  w57 = (- w57 );
  /* #287: (@53[3] += @57) */
  for (rr=w53+3, cs=(&w57); rr!=w53+4; rr+=1) *rr += *cs++;
  /* #288: @39 = (-@39) */
  w39 = (- w39 );
  /* #289: (@53[2] += @39) */
  for (rr=w53+2, cs=(&w39); rr!=w53+3; rr+=1) *rr += *cs++;
  /* #290: @56 = (-@56) */
  w56 = (- w56 );
  /* #291: (@53[1] += @56) */
  for (rr=w53+1, cs=(&w56); rr!=w53+2; rr+=1) *rr += *cs++;
  /* #292: (@53[0] += @37) */
  for (rr=w53+0, cs=(&w37); rr!=w53+1; rr+=1) *rr += *cs++;
  /* #293: @17 = zeros(4x4) */
  casadi_clear(w17, 16);
  /* #294: @14 = @14' */
  /* #295: @17 = mac(@16,@14,@17) */
  for (i=0, rr=w17; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w16+j, ct=w14+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #296: @17 = (2.*@17) */
  for (i=0, rr=w17, cs=w17; i<16; ++i) *rr++ = (2.* *cs++ );
  /* #297: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #298: {@16, @14, @11, @15} = horzsplit(@18) */
  casadi_copy(w18, 4, w16);
  casadi_copy(w18+4, 4, w14);
  casadi_copy(w18+8, 4, w11);
  casadi_copy(w18+12, 4, w15);
  /* #299: @15 = @15' */
  /* #300: {@37, @56, @39, @57} = horzsplit(@15) */
  w37 = w15[0];
  w56 = w15[1];
  w39 = w15[2];
  w57 = w15[3];
  /* #301: (@53[4] += @57) */
  for (rr=w53+4, cs=(&w57); rr!=w53+5; rr+=1) *rr += *cs++;
  /* #302: (@53[5] += @39) */
  for (rr=w53+5, cs=(&w39); rr!=w53+6; rr+=1) *rr += *cs++;
  /* #303: @56 = (-@56) */
  w56 = (- w56 );
  /* #304: (@53[6] += @56) */
  for (rr=w53+6, cs=(&w56); rr!=w53+7; rr+=1) *rr += *cs++;
  /* #305: (@53[7] += @37) */
  for (rr=w53+7, cs=(&w37); rr!=w53+8; rr+=1) *rr += *cs++;
  /* #306: @11 = @11' */
  /* #307: {@37, @56, @39, @57} = horzsplit(@11) */
  w37 = w11[0];
  w56 = w11[1];
  w39 = w11[2];
  w57 = w11[3];
  /* #308: @57 = (-@57) */
  w57 = (- w57 );
  /* #309: (@53[5] += @57) */
  for (rr=w53+5, cs=(&w57); rr!=w53+6; rr+=1) *rr += *cs++;
  /* #310: (@53[4] += @39) */
  for (rr=w53+4, cs=(&w39); rr!=w53+5; rr+=1) *rr += *cs++;
  /* #311: (@53[7] += @56) */
  for (rr=w53+7, cs=(&w56); rr!=w53+8; rr+=1) *rr += *cs++;
  /* #312: (@53[6] += @37) */
  for (rr=w53+6, cs=(&w37); rr!=w53+7; rr+=1) *rr += *cs++;
  /* #313: @14 = @14' */
  /* #314: {@37, @56, @39, @57} = horzsplit(@14) */
  w37 = w14[0];
  w56 = w14[1];
  w39 = w14[2];
  w57 = w14[3];
  /* #315: (@53[6] += @57) */
  for (rr=w53+6, cs=(&w57); rr!=w53+7; rr+=1) *rr += *cs++;
  /* #316: @39 = (-@39) */
  w39 = (- w39 );
  /* #317: (@53[7] += @39) */
  for (rr=w53+7, cs=(&w39); rr!=w53+8; rr+=1) *rr += *cs++;
  /* #318: (@53[4] += @56) */
  for (rr=w53+4, cs=(&w56); rr!=w53+5; rr+=1) *rr += *cs++;
  /* #319: (@53[5] += @37) */
  for (rr=w53+5, cs=(&w37); rr!=w53+6; rr+=1) *rr += *cs++;
  /* #320: @16 = @16' */
  /* #321: {@37, @56, @39, @57} = horzsplit(@16) */
  w37 = w16[0];
  w56 = w16[1];
  w39 = w16[2];
  w57 = w16[3];
  /* #322: @57 = (-@57) */
  w57 = (- w57 );
  /* #323: (@53[7] += @57) */
  for (rr=w53+7, cs=(&w57); rr!=w53+8; rr+=1) *rr += *cs++;
  /* #324: @39 = (-@39) */
  w39 = (- w39 );
  /* #325: (@53[6] += @39) */
  for (rr=w53+6, cs=(&w39); rr!=w53+7; rr+=1) *rr += *cs++;
  /* #326: @56 = (-@56) */
  w56 = (- w56 );
  /* #327: (@53[5] += @56) */
  for (rr=w53+5, cs=(&w56); rr!=w53+6; rr+=1) *rr += *cs++;
  /* #328: (@53[4] += @37) */
  for (rr=w53+4, cs=(&w37); rr!=w53+5; rr+=1) *rr += *cs++;
  /* #329: @37 = (@43/@13) */
  w37  = (w43/w13);
  /* #330: @10 = (@10*@37) */
  w10 *= w37;
  /* #331: (@53[3] += @10) */
  for (rr=w53+3, cs=(&w10); rr!=w53+4; rr+=1) *rr += *cs++;
  /* #332: @10 = (@40/@13) */
  w10  = (w40/w13);
  /* #333: @26 = (@26*@10) */
  w26 *= w10;
  /* #334: (@53[2] += @26) */
  for (rr=w53+2, cs=(&w26); rr!=w53+3; rr+=1) *rr += *cs++;
  /* #335: @26 = (@38/@13) */
  w26  = (w38/w13);
  /* #336: @8 = (@8*@26) */
  w08 *= w26;
  /* #337: (@53[1] += @8) */
  for (rr=w53+1, cs=(&w08); rr!=w53+2; rr+=1) *rr += *cs++;
  /* #338: @8 = sq(@13) */
  w08 = casadi_sq( w13 );
  /* #339: @56 = sq(@7) */
  w56 = casadi_sq( w07 );
  /* #340: @8 = (@8+@56) */
  w08 += w56;
  /* #341: @56 = (@13/@8) */
  w56  = (w13/w08);
  /* #342: @30 = (@30*@37) */
  w30 *= w37;
  /* #343: @29 = (@29*@30) */
  w29 *= w30;
  /* #344: @27 = (@27*@10) */
  w27 *= w10;
  /* #345: @25 = (@25*@27) */
  w25 *= w27;
  /* #346: @29 = (@29+@25) */
  w29 += w25;
  /* #347: @12 = (@12*@26) */
  w12 *= w26;
  /* #348: @3 = (@3*@12) */
  w03 *= w12;
  /* #349: @29 = (@29+@3) */
  w29 += w03;
  /* #350: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #351: @56 = (@56*@29) */
  w56 *= w29;
  /* #352: @56 = (-@56) */
  w56 = (- w56 );
  /* #353: (@53[0] += @56) */
  for (rr=w53+0, cs=(&w56); rr!=w53+1; rr+=1) *rr += *cs++;
  /* #354: @28 = (@28/@13) */
  w28 /= w13;
  /* #355: @28 = (@28*@40) */
  w28 *= w40;
  /* #356: @28 = (-@28) */
  w28 = (- w28 );
  /* #357: @31 = (@31/@13) */
  w31 /= w13;
  /* #358: @31 = (@31*@43) */
  w31 *= w43;
  /* #359: @28 = (@28-@31) */
  w28 -= w31;
  /* #360: @9 = (@9/@13) */
  w09 /= w13;
  /* #361: @9 = (@9*@38) */
  w09 *= w38;
  /* #362: @28 = (@28-@9) */
  w28 -= w09;
  /* #363: @7 = (@7/@8) */
  w07 /= w08;
  /* #364: @7 = (@7*@29) */
  w07 *= w29;
  /* #365: @28 = (@28+@7) */
  w28 += w07;
  /* #366: @28 = (@28/@13) */
  w28 /= w13;
  /* #367: @4 = (@28*@4) */
  for (i=0, rr=w04, cs=w04; i<3; ++i) (*rr++)  = (w28*(*cs++));
  /* #368: (@53[1:4] += @4) */
  for (rr=w53+1, cs=w04; rr!=w53+4; rr+=1) *rr += *cs++;
  /* #369: @35 = mac(@23,@53,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w23+j, ct=w53+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #370: (@34[:8] += @35) */
  for (rr=w34+0, cs=w35; rr!=w34+8; rr+=1) *rr += *cs++;
  /* #371: {@28, @13, @7, @29, @8, @9, @38, @31, @43, @40, @56, @3, @12, @26, @25} = vertsplit(@34) */
  w28 = w34[0];
  w13 = w34[1];
  w07 = w34[2];
  w29 = w34[3];
  w08 = w34[4];
  w09 = w34[5];
  w38 = w34[6];
  w31 = w34[7];
  w43 = w34[8];
  w40 = w34[9];
  w56 = w34[10];
  w03 = w34[11];
  w12 = w34[12];
  w26 = w34[13];
  w25 = w34[14];
  /* #372: @0 = (@0+@25) */
  w00 += w25;
  /* #373: @59 = vertcat(@51, @2, @33, @32, @28, @13, @7, @29, @8, @9, @38, @31, @43, @40, @56, @3, @12, @26, @0) */
  rr=w59;
  *rr++ = w02;
  *rr++ = w33;
  *rr++ = w32;
  *rr++ = w28;
  *rr++ = w13;
  *rr++ = w07;
  *rr++ = w29;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w38;
  *rr++ = w31;
  *rr++ = w43;
  *rr++ = w40;
  *rr++ = w56;
  *rr++ = w03;
  *rr++ = w12;
  *rr++ = w26;
  *rr++ = w00;
  /* #374: @6 = dense(@59) */
  casadi_densify(w59, casadi_s0, w06, 0);
  /* #375: output[1][0] = @6 */
  casadi_copy(w06, 19, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 23;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 562;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 23*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 17*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 562*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
