/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {53, 1, 1};

static const casadi_real casadi_c0[3] = {-3.2843418999917890e+02, -2.1978939779902899e+02, -3.5461621659958513e+02};
static const casadi_real casadi_c1[9] = 
  {3.0447500000000001e-03, 0., 0., 0., 4.5498099999999996e-03, 0., 0., 0.,
  2.8199499999999999e-03};
static const casadi_real casadi_c2[3] = {3.2843418999917890e+02, 2.1978939779902899e+02, 3.5461621659958513e+02};
static const casadi_real casadi_c3[3] = {0., 0., 1.};

/* f_quat:(i0[8])->(o0[4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  return 0;
}

/* f_rot_inv:(i0[4],i1[3])->(o0[3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+4, *w01=w+8, *w02=w+12, w03, w04, w05, w06, *w07=w+20, w08, w09, *w10=w+26;
  casadi_real *w11=w+30, *w12=w+34, *w13=w+38, *w14=w+54, *w15=w+70;
  const casadi_real *cs, *ct;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w00, 4);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w01, 4);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 4, w02);
  /* #3: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #4: @4 = @2[1] */
  for (rr=(&w04), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #5: @5 = @2[2] */
  for (rr=(&w05), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #6: @6 = @2[3] */
  for (rr=(&w06), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #7: @7 = horzcat(@3, @4, @5, @6) */
  rr=w07;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  /* #8: @7 = @7' */
  /* #9: @3 = (-@4) */
  w03 = (- w04 );
  /* #10: @8 = @2[0] */
  for (rr=(&w08), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #11: @9 = (-@5) */
  w09 = (- w05 );
  /* #12: @10 = horzcat(@3, @8, @6, @9) */
  rr=w10;
  *rr++ = w03;
  *rr++ = w08;
  *rr++ = w06;
  *rr++ = w09;
  /* #13: @10 = @10' */
  /* #14: @6 = (-@6) */
  w06 = (- w06 );
  /* #15: @8 = @2[0] */
  for (rr=(&w08), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #16: @11 = horzcat(@9, @6, @8, @4) */
  rr=w11;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w08;
  *rr++ = w04;
  /* #17: @11 = @11' */
  /* #18: @9 = @2[0] */
  for (rr=(&w09), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #19: @12 = horzcat(@6, @5, @3, @9) */
  rr=w12;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w09;
  /* #20: @12 = @12' */
  /* #21: @13 = horzcat(@7, @10, @11, @12) */
  rr=w13;
  for (i=0, cs=w07; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #22: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #23: @6 = 0 */
  w06 = 0.;
  /* #24: @15 = input[1][0] */
  casadi_copy(arg[1], 3, w15);
  /* #25: @7 = vertcat(@6, @15) */
  rr=w07;
  *rr++ = w06;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #26: @1 = mac(@14,@7,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w14+j, ct=w07+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #27: @6 = @1[0] */
  for (rr=(&w06), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #28: @5 = @1[1] */
  for (rr=(&w05), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #29: @5 = (-@5) */
  w05 = (- w05 );
  /* #30: @3 = @1[2] */
  for (rr=(&w03), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #31: @3 = (-@3) */
  w03 = (- w03 );
  /* #32: @9 = @1[3] */
  for (rr=(&w09), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #33: @9 = (-@9) */
  w09 = (- w09 );
  /* #34: @7 = horzcat(@6, @5, @3, @9) */
  rr=w07;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w09;
  /* #35: @7 = @7' */
  /* #36: @6 = @1[1] */
  for (rr=(&w06), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #37: @5 = @1[0] */
  for (rr=(&w05), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #38: @3 = @1[3] */
  for (rr=(&w03), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #39: @3 = (-@3) */
  w03 = (- w03 );
  /* #40: @9 = @1[2] */
  for (rr=(&w09), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #41: @10 = horzcat(@6, @5, @3, @9) */
  rr=w10;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w09;
  /* #42: @10 = @10' */
  /* #43: @6 = @1[2] */
  for (rr=(&w06), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #44: @5 = @1[3] */
  for (rr=(&w05), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #45: @3 = @1[0] */
  for (rr=(&w03), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #46: @9 = @1[1] */
  for (rr=(&w09), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #47: @9 = (-@9) */
  w09 = (- w09 );
  /* #48: @11 = horzcat(@6, @5, @3, @9) */
  rr=w11;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w09;
  /* #49: @11 = @11' */
  /* #50: @6 = @1[3] */
  for (rr=(&w06), cs=w01+3; cs!=w01+4; cs+=1) *rr++ = *cs;
  /* #51: @5 = @1[2] */
  for (rr=(&w05), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #52: @5 = (-@5) */
  w05 = (- w05 );
  /* #53: @3 = @1[1] */
  for (rr=(&w03), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #54: @9 = @1[0] */
  for (rr=(&w09), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #55: @1 = horzcat(@6, @5, @3, @9) */
  rr=w01;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w09;
  /* #56: @1 = @1' */
  /* #57: @14 = horzcat(@7, @10, @11, @1) */
  rr=w14;
  for (i=0, cs=w07; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<4; ++i) *rr++ = *cs++;
  /* #58: @13 = @14' */
  for (i=0, rr=w13, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #59: @0 = mac(@13,@2,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w13+j, ct=w02+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #60: @15 = @0[1:4] */
  for (rr=w15, cs=w00+1; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #61: output[0][0] = @15 */
  casadi_copy(w15, 3, res[0]);
  return 0;
}

/* quadrotor_impl_dae_fun:(i0[15],i1[15],i2[4],i3[],i4[],i5[53])->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, w13, w14, *w15=w+88, *w16=w+103, *w17=w+111, *w18=w+115, *w19=w+119, *w20=w+123, *w21=w+127;
  casadi_real *w22=w+143, *w23=w+159, *w24=w+191, *w25=w+223, *w26=w+239, *w27=w+271, *w28=w+335, w29, w30, *w31=w+401, *w32=w+409, *w33=w+424;
  casadi_real *w34=w+427, *w35=w+430, *w37=w+442;
  const casadi_real **arg1=arg+6, *cs, *ct, *wr36;
  /* #0: @0 = input[1][0] */
  w00 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w01 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w02 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w03 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w04 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w05 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w06 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w07 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = input[1][8] */
  w08 = arg[1] ? arg[1][8] : 0;
  /* #9: @9 = input[1][9] */
  w09 = arg[1] ? arg[1][9] : 0;
  /* #10: @10 = input[1][10] */
  w10 = arg[1] ? arg[1][10] : 0;
  /* #11: @11 = input[1][11] */
  w11 = arg[1] ? arg[1][11] : 0;
  /* #12: @12 = input[1][12] */
  w12 = arg[1] ? arg[1][12] : 0;
  /* #13: @13 = input[1][13] */
  w13 = arg[1] ? arg[1][13] : 0;
  /* #14: @14 = input[1][14] */
  w14 = arg[1] ? arg[1][14] : 0;
  /* #15: @15 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w15;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #16: @0 = 0.5 */
  w00 = 5.0000000000000000e-01;
  /* #17: @16 = zeros(8x1) */
  casadi_clear(w16, 8);
  /* #18: @1 = input[0][0] */
  w01 = arg[0] ? arg[0][0] : 0;
  /* #19: @2 = input[0][1] */
  w02 = arg[0] ? arg[0][1] : 0;
  /* #20: @3 = (-@2) */
  w03 = (- w02 );
  /* #21: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #22: @5 = (-@4) */
  w05 = (- w04 );
  /* #23: @6 = input[0][3] */
  w06 = arg[0] ? arg[0][3] : 0;
  /* #24: @7 = (-@6) */
  w07 = (- w06 );
  /* #25: @17 = horzcat(@1, @3, @5, @7) */
  rr=w17;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w07;
  /* #26: @17 = @17' */
  /* #27: @3 = (-@6) */
  w03 = (- w06 );
  /* #28: @18 = horzcat(@2, @1, @3, @4) */
  rr=w18;
  *rr++ = w02;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w04;
  /* #29: @18 = @18' */
  /* #30: @3 = (-@2) */
  w03 = (- w02 );
  /* #31: @19 = horzcat(@4, @6, @1, @3) */
  rr=w19;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w01;
  *rr++ = w03;
  /* #32: @19 = @19' */
  /* #33: @3 = (-@4) */
  w03 = (- w04 );
  /* #34: @20 = horzcat(@6, @3, @2, @1) */
  rr=w20;
  *rr++ = w06;
  *rr++ = w03;
  *rr++ = w02;
  *rr++ = w01;
  /* #35: @20 = @20' */
  /* #36: @21 = horzcat(@17, @18, @19, @20) */
  rr=w21;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  /* #37: @22 = @21' */
  for (i=0, rr=w22, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #38: @21 = zeros(4x4) */
  casadi_clear(w21, 16);
  /* #39: @23 = horzcat(@22, @21) */
  rr=w23;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<16; ++i) *rr++ = *cs++;
  /* #40: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #41: @3 = input[0][4] */
  w03 = arg[0] ? arg[0][4] : 0;
  /* #42: @5 = input[0][5] */
  w05 = arg[0] ? arg[0][5] : 0;
  /* #43: @7 = (-@5) */
  w07 = (- w05 );
  /* #44: @8 = input[0][6] */
  w08 = arg[0] ? arg[0][6] : 0;
  /* #45: @9 = (-@8) */
  w09 = (- w08 );
  /* #46: @10 = input[0][7] */
  w10 = arg[0] ? arg[0][7] : 0;
  /* #47: @11 = (-@10) */
  w11 = (- w10 );
  /* #48: @17 = horzcat(@3, @7, @9, @11) */
  rr=w17;
  *rr++ = w03;
  *rr++ = w07;
  *rr++ = w09;
  *rr++ = w11;
  /* #49: @17 = @17' */
  /* #50: @7 = (-@10) */
  w07 = (- w10 );
  /* #51: @18 = horzcat(@5, @3, @7, @8) */
  rr=w18;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w07;
  *rr++ = w08;
  /* #52: @18 = @18' */
  /* #53: @7 = (-@5) */
  w07 = (- w05 );
  /* #54: @19 = horzcat(@8, @10, @3, @7) */
  rr=w19;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w03;
  *rr++ = w07;
  /* #55: @19 = @19' */
  /* #56: @7 = (-@8) */
  w07 = (- w08 );
  /* #57: @20 = horzcat(@10, @7, @5, @3) */
  rr=w20;
  *rr++ = w10;
  *rr++ = w07;
  *rr++ = w05;
  *rr++ = w03;
  /* #58: @20 = @20' */
  /* #59: @21 = horzcat(@17, @18, @19, @20) */
  rr=w21;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  /* #60: @25 = @21' */
  for (i=0, rr=w25, cs=w21; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #61: @23 = horzcat(@25, @22) */
  rr=w23;
  for (i=0, cs=w25; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<16; ++i) *rr++ = *cs++;
  /* #62: @26 = @23' */
  for (i=0, rr=w26, cs=w23; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #63: @27 = horzcat(@24, @26) */
  rr=w27;
  for (i=0, cs=w24; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<32; ++i) *rr++ = *cs++;
  /* #64: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #65: @7 = 0 */
  w07 = 0.;
  /* #66: @9 = input[0][8] */
  w09 = arg[0] ? arg[0][8] : 0;
  /* #67: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #68: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #69: @13 = 0 */
  w13 = 0.;
  /* #70: @14 = input[0][11] */
  w14 = arg[0] ? arg[0][11] : 0;
  /* #71: @29 = input[0][12] */
  w29 = arg[0] ? arg[0][12] : 0;
  /* #72: @30 = input[0][13] */
  w30 = arg[0] ? arg[0][13] : 0;
  /* #73: @31 = vertcat(@7, @9, @11, @12, @13, @14, @29, @30) */
  rr=w31;
  *rr++ = w07;
  *rr++ = w09;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w29;
  *rr++ = w30;
  /* #74: @16 = mac(@28,@31,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w28+j, ct=w31+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #75: @16 = (@0*@16) */
  for (i=0, rr=w16, cs=w16; i<8; ++i) (*rr++)  = (w00*(*cs++));
  /* #76: @0 = input[0][14] */
  w00 = arg[0] ? arg[0][14] : 0;
  /* #77: @32 = vertcat(@1, @2, @4, @6, @3, @5, @8, @10, @9, @11, @12, @14, @29, @30, @0) */
  rr=w32;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w00;
  /* #78: @17 = @32[:4] */
  for (rr=w17, cs=w32+0; cs!=w32+4; cs+=1) *rr++ = *cs;
  /* #79: @1 = 10 */
  w01 = 10.;
  /* #80: @2 = 1 */
  w02 = 1.;
  /* #81: @4 = ||@17||_F */
  w04 = casadi_norm_2(4, w17);
  /* #82: @2 = (@2-@4) */
  w02 -= w04;
  /* #83: @1 = (@1*@2) */
  w01 *= w02;
  /* #84: @17 = (@17*@1) */
  for (i=0, rr=w17; i<4; ++i) (*rr++) *= w01;
  /* #85: @18 = zeros(4x1) */
  casadi_clear(w18, 4);
  /* #86: @31 = vertcat(@17, @18) */
  rr=w31;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  /* #87: @16 = (@16+@31) */
  for (i=0, rr=w16, cs=w31; i<8; ++i) (*rr++) += (*cs++);
  /* #88: @33 = 
  [[-328.434, 00, 00], 
   [00, -219.789, 00], 
   [00, 00, -354.616]] */
  casadi_copy(casadi_c0, 3, w33);
  /* #89: @33 = nonzeros(@33) */
  /* #90: @34 = @32[8:11] */
  for (rr=w34, cs=w32+8; cs!=w32+11; cs+=1) *rr++ = *cs;
  /* #91: @33 = (@33*@34) */
  for (i=0, rr=w33, cs=w34; i<3; ++i) (*rr++) *= (*cs++);
  /* #92: @1 = @33[1] */
  for (rr=(&w01), cs=w33+1; cs!=w33+2; cs+=1) *rr++ = *cs;
  /* #93: @35 = zeros(3x1) */
  casadi_clear(w35, 3);
  /* #94: @36 = 
  [[0.00304475, 0, 0], 
   [0, 0.00454981, 0], 
   [0, 0, 0.00281995]] */
  wr36 = casadi_c1;
  /* #95: @35 = mac(@36,@34,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr36+j, ct=w34+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #96: @2 = @35[2] */
  for (rr=(&w02), cs=w35+2; cs!=w35+3; cs+=1) *rr++ = *cs;
  /* #97: @4 = (@1*@2) */
  w04  = (w01*w02);
  /* #98: @6 = @33[2] */
  for (rr=(&w06), cs=w33+2; cs!=w33+3; cs+=1) *rr++ = *cs;
  /* #99: @3 = @35[1] */
  for (rr=(&w03), cs=w35+1; cs!=w35+2; cs+=1) *rr++ = *cs;
  /* #100: @5 = (@6*@3) */
  w05  = (w06*w03);
  /* #101: @4 = (@4-@5) */
  w04 -= w05;
  /* #102: @5 = @35[0] */
  for (rr=(&w05), cs=w35+0; cs!=w35+1; cs+=1) *rr++ = *cs;
  /* #103: @6 = (@6*@5) */
  w06 *= w05;
  /* #104: @8 = @33[0] */
  for (rr=(&w08), cs=w33+0; cs!=w33+1; cs+=1) *rr++ = *cs;
  /* #105: @2 = (@8*@2) */
  w02  = (w08*w02);
  /* #106: @6 = (@6-@2) */
  w06 -= w02;
  /* #107: @8 = (@8*@3) */
  w08 *= w03;
  /* #108: @1 = (@1*@5) */
  w01 *= w05;
  /* #109: @8 = (@8-@1) */
  w08 -= w01;
  /* #110: @33 = vertcat(@4, @6, @8) */
  rr=w33;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w08;
  /* #111: @35 = 
  [[328.434, 00, 00], 
   [00, 219.789, 00], 
   [00, 00, 354.616]] */
  casadi_copy(casadi_c2, 3, w35);
  /* #112: @35 = nonzeros(@35) */
  /* #113: @4 = input[2][0] */
  w04 = arg[2] ? arg[2][0] : 0;
  /* #114: @6 = input[2][1] */
  w06 = arg[2] ? arg[2][1] : 0;
  /* #115: @8 = input[2][2] */
  w08 = arg[2] ? arg[2][2] : 0;
  /* #116: @1 = input[2][3] */
  w01 = arg[2] ? arg[2][3] : 0;
  /* #117: @17 = vertcat(@4, @6, @8, @1) */
  rr=w17;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w08;
  *rr++ = w01;
  /* #118: @34 = @17[1:4] */
  for (rr=w34, cs=w17+1; cs!=w17+4; cs+=1) *rr++ = *cs;
  /* #119: @35 = (@35*@34) */
  for (i=0, rr=w35, cs=w34; i<3; ++i) (*rr++) *= (*cs++);
  /* #120: @33 = (@33+@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #121: @6 = (@29*@12) */
  w06  = (w29*w12);
  /* #122: @8 = (@30*@11) */
  w08  = (w30*w11);
  /* #123: @6 = (@6-@8) */
  w06 -= w08;
  /* #124: @30 = (@30*@9) */
  w30 *= w09;
  /* #125: @12 = (@14*@12) */
  w12  = (w14*w12);
  /* #126: @30 = (@30-@12) */
  w30 -= w12;
  /* #127: @14 = (@14*@11) */
  w14 *= w11;
  /* #128: @29 = (@29*@9) */
  w29 *= w09;
  /* #129: @14 = (@14-@29) */
  w14 -= w29;
  /* #130: @35 = vertcat(@6, @30, @14) */
  rr=w35;
  *rr++ = w06;
  *rr++ = w30;
  *rr++ = w14;
  /* #131: @6 = 9.81 */
  w06 = 9.8100000000000005e+00;
  /* #132: @31 = @32[:8] */
  for (rr=w31, cs=w32+0; cs!=w32+8; cs+=1) *rr++ = *cs;
  /* #133: @17 = f_quat(@31) */
  arg1[0]=w31;
  res1[0]=w17;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #134: @34 = [0, 0, 1] */
  casadi_copy(casadi_c3, 3, w34);
  /* #135: @37 = f_rot_inv(@17, @34) */
  arg1[0]=w17;
  arg1[1]=w34;
  res1[0]=w37;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #136: @37 = (@6*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w06*(*cs++));
  /* #137: @35 = (@35-@37) */
  for (i=0, rr=w35, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #138: @37 = [0, 0, 1] */
  casadi_copy(casadi_c3, 3, w37);
  /* #139: @6 = 1.19 */
  w06 = 1.1899999999999999e+00;
  /* #140: @6 = (@0/@6) */
  w06  = (w00/w06);
  /* #141: @37 = (@37*@6) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) *= w06;
  /* #142: @35 = (@35+@37) */
  for (i=0, rr=w35, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #143: @4 = (@4-@0) */
  w04 -= w00;
  /* #144: @0 = 0.111136 */
  w00 = 1.1113601255016600e-01;
  /* #145: @4 = (@4/@0) */
  w04 /= w00;
  /* #146: @32 = vertcat(@16, @33, @35, @4) */
  rr=w32;
  for (i=0, cs=w16; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  *rr++ = w04;
  /* #147: @15 = (@15-@32) */
  for (i=0, rr=w15, cs=w32; i<15; ++i) (*rr++) -= (*cs++);
  /* #148: output[0][0] = @15 */
  casadi_copy(w15, 15, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 445;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 445*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
